### ISSUE TITLE
PaLM API Example

### ISSUE THREAD

**Issue by shakeel143** [dsdanielpark/Bard-API#100]
I am android developer, i have tried to find the bard api, after long time i got the Palm api
here it is
https://makersuite.google.com/app/library

**Comment by pixkk** [comment]
You must be approved in whitelist

**Comment by dsdanielpark** [comment]
![palm2gif](https://github.com/dsdanielpark/Bard-API/assets/81407603/430a7e9b-3651-4dfb-9d17-b75cc278fa70)


I have just approved the waitlist for Google's palm2, and we have conducted a successful test. The pertinent information has been added to the Bard-API repository.

If you felt differently from what I experienced, could you freely share what you felt and also provide reasons for it?
https://github.com/dsdanielpark/Bard-API/discussions/102

**Comment by shakeel143** [comment]
Great explainaton, yes i am also approved the waitlist. i just want to integrate into android app.

**Comment by stubbi** [comment]
Can you add images to the prompt in palm2?

**Comment by shakeel143** [comment]
> 

@stubbi  , i have not tried images but bard is not accepting images..

**Comment by Rahul-singh7906** [comment]
how can we use image prompt in PaLM api?

**Comment by shakeel143** [comment]
> @shakeel143 @stubbi how can we use image prompt in PaLM api?

Dear i am not getting how we can use image, if you got must share here.

**Comment by kientv** [comment]
I see that bard is better than palm, right?

**Comment by Gunjitbedi** [comment]
It doesn't seem like PALM2 has access to internet to answer real time questions like BARD. Any work around to get real time answers via PALM2?

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```
