### ISSUE TITLE
Can't connect to bot via proxy

### ISSUE THREAD

**Issue by OlegRuban-ai** [dsdanielpark/Bard-API#104]
I have a proxy with http/socks5 and login/password authorization. How do I pass data to connect to Bard? I try structure:

```
{'http': 'http://login:password@host:port',
'socks5': 'socks5://login:password@host:port'}
```

But after the request, I get the following response:

Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",99],["af.httprm",99,"-1096231913768114475",16]]\n25\n[["e",4,null,null,131]]\n'. 
Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.

**Comment by piccolo20** [comment]
Same error when I deployed the code on the hosting.

**Comment by dsdanielpark** [comment]
This error is not caused by the package itself. However, a definitive solution to this error has not been found yet. In most cases, it either resolves as a temporary error (temporary account restrictions) or by using a different account, or by modifying network settings.

**Comment by OlegRuban-ai** [comment]
It turns out that it only works on localhost and the proxy does not help in any way. How many requests per minute, hour and day can be sent without the risk of account blocking?
