### ISSUE TITLE
'Bard' object has no attribute 'speech'

### ISSUE THREAD

**Issue by Birillox** [dsdanielpark/Bard-API#109]
is it not possible the TTS feature?

**Comment by dsdanielpark** [comment]
This is because we are currently updating the functionalities of the package, which are not supported in previous versions.

Sometimes Python packages are not properly uninstalled and reinstalled during runtime. For TTS, please make sure to reinstall and check if the version is 0.1.25 or higher.

```
$ pip install bardapi>=0.1.25
```
