### ISSUE TITLE
404 Client Error: Not Found for url: https://content-push.googleapis.com/upload/

### ISSUE THREAD

**Issue by Enderfga** [dsdanielpark/Bard-API#112]
I only successfully uploaded a picture once, but I can no longer use it starting from the second attempt.

**Comment by phamxtien** [comment]
I got error:
404 Client Error: Not Found for url: https://content-push.googleapis.com/upload/

**Comment by Enderfga** [comment]
I found some reasons for the "Method Not Allowed" error. I need to create a new bard object every time. However, this does not completely solve the problem, and the "Response code not 200" and "Response Status is 429" issues still occur.

**Comment by dsdanielpark** [comment]
*It may not work as it is only available for certain accounts, regions, and other restrictions.*

Moreover, since I cannot invoke the method in my region and account, I have no choice but to rely on the contributors' debugging. I am eagerly awaiting contributions from an active community. 

Thank you in advance for your contribution.

**Comment by dsdanielpark** [comment]
[thewh1teagle](https://github.com/thewh1teagle) Could you kindly check this issue?

**Comment by Yazeed-Alharbi** [comment]
I am encountering the same problem. The first request is uploaded successfully, other than that it will always show 404 Client Error: Not Found for url: https://content-push.googleapis.com/upload/

**Comment by senseibence** [comment]
I am also encountering the same issue. I have tried:

1) Continuing the chat session
2) Creating a new chat session

And for both scenarios, I have tried using the same Bard object and tried creating a new Bard object within the same script. Furthermore, I have tried adding timeout=30 and tried forcing ~30 seconds of sleep before sending another image. However, I continue to receive `404 Client Error: Not Found for url: https://content-push.googleapis.com/upload/`, and am unable to send consecutive images from a single script. 

Restarting the script allows for multiple new-chat image uploads. Multiple uploads from within a single script do not appear to work. I will try looking further into why `resp.raise_for_status()` raised this error in the `_upload_image` method.

**Comment by elinalai0000** [comment]
> I am also encountering the same issue. I have tried:
> 
> 1. Continuing the chat session
> 2. Creating a new chat session
> 
> And for both scenarios, I have tried using the same Bard object and tried creating a new Bard object within the same script. Furthermore, I have tried adding timeout=30 and tried forcing ~30 seconds of sleep before sending another image. However, I continue to receive `404 Client Error: Not Found for url: https://content-push.googleapis.com/upload/`, and am unable to send consecutive images from a single script.
> 
> Restarting the script allows for multiple new-chat image uploads. Multiple uploads from within a single script do not appear to work. I will try looking further into why `resp.raise_for_status()` raised this error in the `_upload_image` method.

**Insert the following code  in the _upload_image method and it will work:**
`headers['x-goog-upload-command'] = 'start'`

![image](https://github.com/dsdanielpark/Bard-API/assets/132626578/6e2581ef-2e16-4918-b736-eacc0c6dff01)
