### ISSUE TITLE
Multimodal capability

### ISSUE THREAD

**Issue by Lucky-Lance** [dsdanielpark/Bard-API#116]
Does your API support multimodal input, such as image input for bard?

**Comment by mattbarron** [comment]
The API does support multimodal as of 0.1.27. See here: https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method

**Comment by Lucky-Lance** [comment]
Wonderful, thanks for your timely response

**Comment by Rahul-singh7906** [comment]
> The API does support multimodal as of 0.1.27. See here: https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method

@mattbarron, but this ask_about_image feature is not working with bard.
I am facing this error: 
<img width="532" alt="issue" src="https://github.com/dsdanielpark/Bard-API/assets/91553428/dc401bb7-7a62-409f-b216-b663ff82b207">

**Comment by veonua** [comment]
Response Error: b')]}\'\n\n103\n[["er",null,null,null,null,400,null,null,null,3],["di",39],["af.httprm",39,"2222994121278587289",11]]\n25\n[["e",4,null,null,139]]\n'. 
Unable to get response.
Please double-check the cookie values and verify your network environment or google account.

the same image works ok on the webUI

**Comment by veonua** [comment]
+ should be fixed now in the main branch

**Comment by dsdanielpark** [comment]
This feature, while incomplete, has been updated in the main branch and is testable in the latest release, which is version 0.1.39. Thank you.

## Bard API - version 0.1.39

```
$ pip install bardapi==0.1.39
```
```
$ pip install -q -U bardapi
```
