### ISSUE TITLE
Exception: Response code not 200. Response Status is 429

### ISSUE THREAD

**Issue by Birillox** [dsdanielpark/Bard-API#117]
I got this error when i try to request something to Bard.
I tried with new token but nothing..

**Comment by LucasDarie** [comment]
The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by Abhineetnehra** [comment]
Response status 429 is too much frequent after  bard's new update. It seems google extensively limited the request count.

**Comment by basimslam** [comment]
is there a fix to this?

**Comment by Birillox** [comment]
Just wait about 10-20minutes.
If you are using some service like ngrok, just reset all and it s ok

Il Sab 5 Ago 2023, 14:12 Basim Aslam ***@***.***> ha scritto:

**Comment by Nipun1212** [comment]
Hi I recently started facing the same issue, I have a web app on pythonanywhere, and im able to run the chatbot through my own vs code environment, but when I try in my flask application, I get Exception: Response code not 200. Response Status is 429

**Comment by Birillox** [comment]
Just try to restart all your server/app

Il Dom 27 Ago 2023, 13:12 Nipun Bhatia ***@***.***> ha
scritto:

**Comment by Nipun1212** [comment]
I have restarted it several times, still leading to this error, even refreshed cookies.
It just seems to happen on the deployed web app, it seems to work fine on my own Jupyter notebook.
Any fix for that?

**Comment by Nipun1212** [comment]
Hi, any fixes for this issue, still persists

**Comment by marcosalvadori** [comment]
Probably no fixes is possible. Google limit the use and there are no possibilities.

**Comment by Antom91** [comment]
I only send 5 requests and got the same error :-1:

**Comment by acon10** [comment]
I received same error with different account

**Comment by Ducvoccer** [comment]
any update?

**Comment by acon10** [comment]
I resolved the issue in my code. Please avoid to use Bard() obj inside loop. I made this mistake. After I define Bard() as global variables(outside loop), my code is fixed.

**Comment by luoysuan** [comment]
After I changed the proxy ip, I can use it normally again

**Comment by aakarshh2006** [comment]
from bardapi import Bard
import os

os.environ["_BARD_API_KEY"] = "g.a000gAhy-nPoBCcysK9fKl1k7WDo73jw6XjgjrmVYJTh0HqGWuoS5rdy8ZW9hNCJaQIQH_u11QACgYKAasSAQASFQHGX2MiSTmhMyywDGTmINofYYpNoxoVAUF8yKofFQj67HivGBVSGe9UQ7_a0076."

message = input("ENTER : ")
print(Bard().get_answer(str(message)))

using this code and getting the same error of respond status code

**Comment by acon10** [comment]
Bard was decommisioned. 

Generate your api key here: https://makersuite.google.com/app/apikey?hl=en

Instead you must use Gemini api key by the following sample instead:

genai.configure(api_key="YOUR API KEY")  
generation_config = {"temperature": 0.9, "top_p": 1, "top_k": 1, "max_output_tokens": 2048}
model = genai.GenerativeModel("gemini-pro", generation_config = generation_config)

response = model.generate_content("tell me some story")
print(response.text)
