### ISSUE TITLE
Noob question, Can I import the Bard library into Typescript without installing locally?

### ISSUE THREAD

**Issue by natea11** [dsdanielpark/Bard-API#122]
Hello,

Thank you for your time.  I asked Bard if it works with Typescript and it gave me this code:

```
import { bard } from 'google.cloud.bard';

const poem = bard.generate('Write me a poem about love.');

console.log(poem);
```

But when I try to run it, I  receive this error:
```
error: Relative import path "google.cloud.bard" not prefixed with / or ./ or ../
```

Is there a way I can import the API without installing locally?

**Comment by dsdanielpark** [comment]
https://github.com/dsdanielpark/Bard-API/blob/main/translate_to/bardapi.TS

You can tránlate this pỷthon code to the other programming language using other gẻnerative AI like chảt GPT.

**Comment by natea11** [comment]
Thanks.
