### ISSUE TITLE
Temporarily unavailable due to traffic or cookie issues

### ISSUE THREAD

**Issue by vayvaychicken** [dsdanielpark/Bard-API#126]
When running the API, I get this error:
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n56\n[["di",77],["af.httprm",77,"-6224477002209243600",24]]\n25\n[["e",4,null,null,131]]\n'.
Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.

I've triple checked that the cookie value is correct. I had this error when first using the API, and then it seemed to resolve but now it has come back. I am in the US so I'm not sure whether just to wait or if there is some solution that I can't figure out. Thank you!

**Comment by vayvaychicken** [comment]
I'm noticing that Bard is not working from the Google website, which may be the issue.

**Comment by senseibence** [comment]
> When running the API, I get this error: Response Error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n56\n[["di",77],["af.httprm",77,"-6224477002209243600",24]]\n25\n[["e",4,null,null,131]]\n'. Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.
> 
> I've triple checked that the cookie value is correct. I had this error when first using the API, and then it seemed to resolve but now it has come back. I am in the US so I'm not sure whether just to wait or if there is some solution that I can't figure out. Thank you!

I was getting this error after sending many requests in a short amount of time. I switched Google accounts and got a new cookie value from bard.google.com and just took more time between requests. Error still occasionally happens, but waiting a moment and resending the request works for me.

This may not apply to your situation specifically.

**Comment by vayvaychicken** [comment]
This worked, I had to go into safari because the cookie would not refresh in a new google account for some reason but it worked after that. thanks!

**Comment by nguyenduclong1147** [comment]
The problem is not with cookies. I found out that bard blocks questions that are repeated after multiple times. Just change the question form but keep the meaning the same.
