### ISSUE TITLE
Unable to get respones from get_answer api

### ISSUE THREAD

**Issue by kaka1346** [dsdanielpark/Bard-API#129]
Please check get_answer api. I can not get respones from this api. 
Error :
 File .../bardapi/core.py,  line 144, in get_answer
resp_dict = json.loads(resp.content.splitlines()[3][0][2]
IndexError: list index out of range

**Comment by dsdanielpark** [comment]
Bard API version might not have been updated properly. The content on line [144 of core.py](https://github.com/dsdanielpark/Bard-API/blob/main/bardapi/core.py#L144) is not the same as above. 

It's possible that an older version is still running. 

Please reconfigure the environment or check the version of bardapi and update it to the latest version. 
You can verify the version and reinstall or upgrade the package using the following commands.




```python
import bardapi
print(bardapi.__version__)
```


```
$ pip uninstall bardapi
$ pip install git+https://github.com/dsdanielpark/Bard-API.git
```

```
$ pip install -U git+https://github.com/dsdanielpark/Bard-API.git
```
