### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by menlis-smith** [dsdanielpark/Bard-API#131]
On line 147 of core.py

`resp_dict = json.loads(resp.content.splitlines()[3])[0][2]`

An error

`IndexError: list index out of range`

**Comment by kshitijaucharmal** [comment]
Just got the same error, what's up with this?

**Comment by kshitijaucharmal** [comment]
Found the problem, somehow the cookie is changed. Find the new one and replace the token used by bard :)
