### ISSUE TITLE
use in firebase functions not possible

### ISSUE THREAD

**Issue by stubbi** [dsdanielpark/Bard-API#134]
When using firebase functions, one has to use `requirements.txt`. So it's not possible (at least afaik) to exclude the dependency as suggested in https://github.com/dsdanielpark/Bard-API/issues/93#issuecomment-1624085878. I wonder why [`google-cloud-translate` is fixed to version `2.0.1`](https://github.com/dsdanielpark/Bard-API/blob/main/setup.py#L43) and if that constraint could be relaxed?

`requirements.txt`:

```
firebase_functions
bardapi~=0.1.29
```

`pip install -r requirements.txt` leading to

```
ERROR: Cannot install firebase_functions and google-cloud-translate==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    google-cloud-firestore 2.11.0 depends on google-api-core[grpc]!=2.0.*, !=2.1.*, !=2.10.*, !=2.2.*, !=2.3.*, !=2.4.*, !=2.5.*, !=2.6.*, !=2.7.*, !=2.8.*, !=2.9.*, <3.0.0dev and >=1.34.0
    google-cloud-translate 2.0.1 depends on google-api-core[grpc]<2.0.0dev and >=1.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by dsdanielpark** [comment]
To resolve multiple version conflict errors, we enforced a specific version; This error has been reported in very few environments. Nevertheless, considering that there are not many users utilizing the `Google Cloud Translate` package, we have decided to remove the forced version.

This issue has been resolved in commit hash e8766ed179655f094f7aa538ba7ffebcc0a7d12c.

Simply install bardapi as follows, and then install the appropriate version of dependency packages based on the messages displayed afterwards.

### Install Bard API without dependencies
```
pip install bardapi==0.1.29 --no-deps
```
