### ISSUE TITLE
Unable to install Bard-Api - Windows 10 - Python 3.9.1

### ISSUE THREAD

**Issue by Alexo47** [dsdanielpark/Bard-API#136]
Hello!

I downloaded the code and unzipped it to a particular folder then in a windows 10 command prompt I navigate to the folder and entered the command:
python -m pip install bard-api --user

I get this error message:
ERROR: Could not find a version that satisfies the requirement bard-api (from versions: none)
ERROR: No matching distribution found for bard-api

My Python version is  3.9.1

Can someone help me on this issue?

I thank you for your attention and look forward for a feedback.

Cordially,
Alexandre

**Comment by dsdanielpark** [comment]
Use this command.


python -m pip install bardapi --user

**Comment by Alexo47** [comment]
Hi dsdanielpark!

Many thanks for your quick feedback.
The install seems ok, but when in Python I run  <import bardapi> I get the error message:
 ModuleNotFoundError: No module named 'google.protobuf'  (see details below)

Your feedback is welcome!
Cordially - Alexandre

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import bardapi

File <frozen zipimport>:259, in load_module(self, fullname)

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\bardapi-0.1.29-py3.9.egg\bardapi\__init__.py:4
      1 # Copyright 2023 parkminwoo, MIT License
      3 import os
----> 4 from bardapi.core import Bard
      5 from bardapi.chat import ChatBard
      6 from bardapi.constants import (
      7     SESSION_HEADERS,
      8     ALLOWED_LANGUAGES,
   (...)
     11     USER_PROMPT,
     12 )

File <frozen zipimport>:259, in load_module(self, fullname)

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\bardapi-0.1.29-py3.9.egg\bardapi\core.py:11
      9 import browser_cookie3
     10 from deep_translator import GoogleTranslator
---> 11 from google.cloud import translate_v2 as translate
     12 from bardapi.constants import ALLOWED_LANGUAGES, SESSION_HEADERS, IMG_UPLOAD_HEADERS
     15 class Bard:

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\google_cloud_translate-3.11.2-py3.9.egg\google\cloud\translate_v2\__init__.py:22
     18 from pkg_resources import get_distribution
     20 __version__ = get_distribution("google-cloud-translate").version
---> 22 from google.cloud.translate_v2.client import Client
     25 __all__ = ("__version__", "Client")

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\google_cloud_translate-3.11.2-py3.9.egg\google\cloud\translate_v2\client.py:19
     15 """Client for interacting with the Google Cloud Translation API."""
     18 import google.api_core.client_options
---> 19 from google.cloud.client import Client as BaseClient
     21 from google.cloud.translate_v2._http import Connection
     24 ENGLISH_ISO_639 = "en"

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\google_cloud_core-2.3.3-py3.9.egg\google\cloud\client\__init__.py:25
     22 from typing import Union
     24 import google.api_core.client_options
---> 25 import google.api_core.exceptions
     26 import google.auth
     27 from google.auth import environment_vars

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\google_api_core-2.12.0.dev0-py3.9.egg\google\api_core\exceptions.py:29
     26 from typing import Union
     27 import warnings
---> 29 from google.rpc import error_details_pb2
     31 try:
     32     import grpc

File c:\users\axdpa\appdata\local\programs\python\python39\lib\site-packages\googleapis_common_protos-1.59.1-py3.9.egg\google\rpc\error_details_pb2.py:20
      1 # -*- coding: utf-8 -*-
      2 
      3 # Copyright 2020 Google LLC
   (...)
     17 # Generated by the protocol buffer compiler.  DO NOT EDIT!
     18 # source: google/rpc/error_details.proto
     19 """Generated protocol buffer code."""
---> 20 from google.protobuf import descriptor as _descriptor
     21 from google.protobuf import descriptor_pool as _descriptor_pool
     22 from google.protobuf import message as _message

ModuleNotFoundError: No module named 'google.protobuf'

**Comment by dsdanielpark** [comment]
For using simple text generation, install `0.1.23alpha` version 
```
$ pip install bardapi==0.1.23a
```

To fix google-cloud-translate confilict, try to insttalll version `2.0.1`
```
$ pip install google-cloud-translate==2.0.1
```

**Comment by Alexo47** [comment]
Hello Daniel!

Thanks for your valuable inputs.

I installed $ pip install bardapi==0.1.23a and the installation seems to 
work.

However, I don't understand the sequence to get the Authentication:
>Warning Do not expose the __Secure-1PSID
>
Visit https://bard.google.com/F12 for consoleSession: Application → 
Cookies → Copy the value of __Secure-1PSID cookie.

=> Could you explain how to get __Secure-1PSID?

I thank you or your attention and look forward for your feedback.

Cordially,
Alexandre D.


------ Original Message ------

**Comment by Alexo47** [comment]
Hello Daniel!

I finally found the right way => for me  <= to find the API key 
__Secure-1PSID

This sequence that shows the cookies:
Visit https://bard.google.com/F12 for consoleSession: STORAGE→ Cookies → 
Copy the value of __Secure-1PSID cookie.


------ Forwarded Message ------
From: "Alexandre Dniestrowski" ***@***.***>
To: "dsdanielpark/Bard-API" 
***@***.***>
Sent: 25/07/2023 16:10:11
Subject: Re[2]: [dsdanielpark/Bard-API] Unable to install Bard-Api - 
Windows 10 - Python 3.9.1 (Issue #136)

Hello Daniel!

Thanks for your valuable inputs.

I installed $ pip install bardapi==0.1.23a and the installation seems to 
work.

However, I don't understand the sequence to get the Authentication:
>Warning Do not expose the __Secure-1PSID
>
Visit https://bard.google.com/F12 for consoleSession: Application → 
Cookies → Copy the value of __Secure-1PSID cookie.

=> Could you explain how to get __Secure-1PSID?

I thank you or your attention and look forward for your feedback.

Cordially,
Alexandre D.


------ Original Message ------

**Comment by felipelourentino** [comment]
Obrigado segui e consegui, nenhuma AI me ajudou kkkk, precisamos de mais programadores que sabem o que está fazendo.

**Comment by GAN-007** [comment]
HEEEELPPP!!!!!! :: from bard import question_answering  # Assuming bard module is imported for question answering
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bard'
YET :: Requirement already satisfied: bard in ./myenv/lib/python3.11/site-packages (0.1)
