### ISSUE TITLE
Exception: SNlM0e value not found.

### ISSUE THREAD

**Issue by GvdDool** [dsdanielpark/Bard-API#143]
Following up on a post from nikk-16 on the same topic:

> **There is no issue int this API.**
> But after excessive usage, the Google knows that cookie is having unauthorized access so the 1PSID is revert in some form.
> 
> The reason we get : Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'
> 
> How can you get rid of it:
> Clear cookies of bard.google.com and again
> 
> - login into the account
> - F12 > Applications > Cookies > bard > __Secure-1PSID
> - Copy cookie and paste into your code.
> 
> Re run and you are good to go.

_Originally posted by @nikk-16 in https://github.com/dsdanielpark/Bard-API/issues/99#issuecomment-1633060128_

My problem is that the cookies seem to expire in 10 minutes and then I have to manually reset the browser (incognito on FireFox) while I am working on a notebook in Chrome. I am more than happy to change my coding environment if this helps, but closing/cleaning/restarting the browser is not very efficient - all suggestions are welcome.

Happy coding,
Gijs

**Comment by thewh1teagle** [comment]
@dsdanielpark 
Looks like Google added captcha into Bard, If you don't send the cookie which solved by captcha manually, Google will response with status `429`

**Comment by GvdDool** [comment]
@dsdanielpark - I know you are busy with another project, but is there a workaround for this problem?

**Comment by GvdDool** [comment]
@dsdanielpark , thank you for the explanation; I will try to keep Bard active on Edge and make it work. Unfortunately, I can't use the official PaLM2 API because it's the active internet link I would like to use for my topic, and the official PaLM2 API is static.
