### ISSUE TITLE
Exception: Can't extract cookie from browsers. Please sign in first at

### ISSUE THREAD

**Issue by freeEDU-Github** [dsdanielpark/Bard-API#144]
I am currently creating a streamlit application with bardapi feature. The code works perfectly in my local pc but when I deployed my app to streamlit cloud, I am encountering some errors

`bard = Bard(token_from_browser=True)`
Exception: Can't extract cookie from browsers. Please sign in first at https://accounts.google.com/v3/signin/identifier?followup=https://bard.google.com/&flowName=GlifWebSignIn&flowEntry=ServiceLogin
Traceback:
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/mount/src/ai-projects-with-gpt-3.5/Visual_LLM/app.py", line 94, in <module>
    main()
File "/mount/src/ai-projects-with-gpt-3.5/Visual_LLM/app.py", line 31, in main
    get_response(response_container, prompt, image)
File "/mount/src/ai-projects-with-gpt-3.5/Visual_LLM/app.py", line 74, in get_response
    bard = Bard(token_from_browser=True)
File "/home/adminuser/venv/lib/python3.9/site-packages/bardapi/core.py", line 49, in __init__
    raise Exception(
  
`token = st.secrets["BARD_API_KEY"]
  bard = Bard(token=token)`
  Response Error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",222],["af.httprm",221,"3083100429511302743",0]]\n25\n[["e",4,null,null,131]]\n'. Unable to get response. Please double-check the cookie values and verify your network environment or google account.
  
Is there any other way to make the token works when deploying to streamlit cloud?

**Comment by miladv33** [comment]
you better update the library. I faced the same issue, and updating it solved it.

**Comment by dsdanielpark** [comment]
1. Please verify that you are using the appropriate version and ensure that the previous version has been correctly removed.
2. Manually try using Bard's methods correctly. `bard = Bard(token="xxxxxx").get_answer("Hi, Bard.")`
3. Clear all browsers, restart, and then access Bard's web UI interface on Google's Bard page to ensure communication is possible.
4. In the above scenario, try different browsers and experiment with various environments, such as renewing cookies (or logging out and logging back in).

Please refer to the notes in the Readme.

Use [browser_cookie3](https://github.com/borisbabic/browser_cookie3) issue page related with [Auto Cookie Bard](https://github.com/dsdanielpark/Bard-API#auto-cookie-bard)

**Comment by dsdanielpark** [comment]
As this feature relies on browser_cookie3, which we can no longer provide support for, we are closing this issue.
