### ISSUE TITLE
unable to retrieve the token

### ISSUE THREAD

**Issue by miladv33** [dsdanielpark/Bard-API#145]
**Describe the bug**.

The token reading error occurs when trying to access the browser's library
I can send messages in the browser and receive a response, yet the library is unable to retrieve the token.

**Version**
OS: Win
Python: 3.11.3
Bard API: =0.1.29
Using proxy: no
Legion:

**Code**
```python
bard = Bard(timeout=20, token_from_browser=True)

```
**Error**
```
    bard = Bard(timeout=20, token_from_browser=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mousavi\AppData\Roaming\Python\Python311\site-packages\bardapi\core.py", line 49, in __init__
    raise Exception(
Exception: 
Can't extract cookies from browsers.
Please sign in first at
https://accounts.google.com/v3/signin/identifier?followup=https://bard.google.com/&flowName=GlifWebSignIn&flowEntry=ServiceLogin
```

**Comment by yihong0618** [comment]
can you use token way?

bard = Bard(token="xxxxx")

**Comment by miladv33** [comment]
I can utilize the token like this:

```
token = 'xxx'
# read 
os.environ['_BARD_API_KEY']= token
bard = Bard(timeout=20)
```

**Comment by dsdanielpark** [comment]
1. Manually try using Bard's methods correctly.
2. Clear all browsers, restart, and then access Bard's web UI interface on Google's Bard page to ensure communication is possible.
3. In the above scenario, try different browsers and experiment with various environments, such as renewing cookies (or logging out and logging back in).

Please refer to the notes in the Readme.

Use [browser_cookie3](https://github.com/borisbabic/browser_cookie3) issue page related with [Auto Cookie Bard](https://github.com/dsdanielpark/Bard-API#auto-cookie-bard)

**Comment by dsdanielpark** [comment]
As this feature relies on browser_cookie3, which we can no longer provide support for, we are closing this issue.
