### ISSUE TITLE
Save all responses with "View other drafts"

### ISSUE THREAD

**Issue by SiyuanHuang95** [dsdanielpark/Bard-API#147]
The Brad website provides the "View other drafts" button to display other draft responses for the same question, which offers great diversity and potentially improved answer accuracy. Would it be possible to also get the other drafts with the API?

**Comment by dsdanielpark** [comment]
The `get_answer` method already returns different options of the text-based AI Bard as a response dictionary. If you have any requests for functionalities other than this, please provide a more detailed explanation.

```python
import os
from bardapi import Bard

token = "xxxxxX"
bard = Bard(token=token)
prompt='What is a LLM?'

responses = bard.get_answer(prompt)['choices']

for choice in responses:
  id = choice['id']
  response = choice['content'][0]
  print(id)
  print(response)
```

**Comment by SiyuanHuang95** [comment]
Aha, I did not notice it.

Thanks for your information!
