### ISSUE TITLE
BardAPI not work on webserver: checked by Google Captcha

### ISSUE THREAD

**Issue by vanthuyta** [dsdanielpark/Bard-API#149]
Thank you for your insteresting API,

Before, I'm running BardAPI on my webserver.
Today, I see that BardAPI has not worked anymore, the response from BardAPI was Captcha html page.

Can you help me to solve this issue?

**Comment by dsdanielpark** [comment]
Have you checked if it's still not possible to make a call even after completing the Captcha? Captcha is designed to be difficult to bypass for non-human entities, which is its purpose.

**Comment by vanthuyta** [comment]
I had to solve manually the captcha for each request working.
If i run the BardAPI on IDE of Python, it works fine without captcha.
