### ISSUE TITLE
Streaming request support

### ISSUE THREAD

**Issue by NullpointerW** [dsdanielpark/Bard-API#156]
wait for totally response data is too long，return part of response data will be quickly and fluently prefer than fetching complete response once，like chatGPT

**Comment by dsdanielpark** [comment]
You can specify the following session object all at once and then receive only responses thereafter, or you can use BardAsync to use Bard asynchronously.

- [Reusable session object](https://github.com/dsdanielpark/Bard-API#reusable-session-object)
- [Bard Async](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#using-bard-asynchronously)
