### ISSUE TITLE
Crash in new released version 

### ISSUE THREAD

**Issue by Yorddyyorddy** [dsdanielpark/Bard-API#160]
AttributeError: 'Bard' object has no attribute 'google_translator_api_key'

    if self.google_translator_api_key is not None:

  File "/usr/local/lib/python3.9/site-packages/bardapi/core.py", line 107, in get_answer

    b = bard.get_answer(text)

  File "/app/helpers/bard.py", line 20, in chatbard

    t = chatbard(m.text,m.from_user.id)

  File "/app/plugins/private.py", line 62, in main_func

    await handler.callback(self.client, *args)

  File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker

Traceback (most recent call last):

'Bard' object has no attribute 'google_translator_api_key

**Comment by Yorddyyorddy** [comment]
AttributeError: 'Bard' object has no attribute 'google_translator_api_key'

    if self.google_translator_api_key is not None:

  File "/usr/local/lib/python3.9/site-packages/bardapi/core.py", line 107, in get_answer

    b = bard.get_answer(text)

  File "/app/helpers/bard.py", line 20, in chatbard

    t = chatbard(m.text,m.from_user.id)

  File "/app/plugins/private.py", line 62, in main_func

    await handler.callback(self.client, *args)

  File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker

Traceback (most recent call last):

'Bard' object has no attribute 'google_translator_api_key

**Comment by dsdanielpark** [comment]
Please try lowering the version and checking first.

```
$ pip install bardapi==0.1.30
```

And if the same error still occurs even after matching the version, please check the refactored version.
```
$ pip install git+https://github.com/dsdanielpark/Bard-API.git
```

Alternatively, you can identify the error and contribute by creating a PR to the Bard API package. Thank you.

**Comment by Yorddyyorddy** [comment]
> 

sorry sir both of them doesn't work , only the alpha release worked for me but I needed the image recognition feature which has not included in alpha version

**Comment by dsdanielpark** [comment]
Will the same error message be shown? If possible, please share the complete code and the error message. 
You can use a screenshot or markdown, whichever is convenient.

**Comment by Yorddyyorddy** [comment]
> Will the same error message be shown? If possible, please share the complete code and the error message. You can use a screenshot or markdown, whichever is convenient.

yeah all i got is the same issue and i am sharing it from the server which i hosted my app there 
but  i am use the alpha version on my android termux as it is not possible to install the current one

**Comment by Yorddyyorddy** [comment]
AttributeError: 'Bard' object has no attribute 'google_translator_api_key'

    if self.google_translator_api_key is not None:

  File "/usr/local/lib/python3.9/site-packages/bardapi/core.py", line 107, in get_answer



check this file i will help after ,now my connection is poor
