### ISSUE TITLE
Add prompt to a specified conversation_id

### ISSUE THREAD

**Issue by vanthuyta** [dsdanielpark/Bard-API#162]
Thank you for your great BardAPI,

I would like to add a prompt to a specified conversation_id, I have tried "Fix Conversation ID (Fix Context)", I see the new prompt can be added to an conversation_id, but insteads of adding, it deleted old prompts and responses in that conversation_id and replaced by new one. 

Could you please update this feature?

Thank you very much!

**Comment by dsdanielpark** [comment]
Thank you very much. 

Would you be able to share the code you are currently using for the situation in the field of Computer Science?
By utilizing Reusable Session and Fix Conversation appropriately, it seems that the current deployed code could also be used. 

As there has been one more request for this, I will take this request to investigate once again.
