### ISSUE TITLE
Request Bard API Key

### ISSUE THREAD

**Issue by carganillox** [dsdanielpark/Bard-API#168]
Name : Joms
Email: carganillo@gmail.com
Purpose : Educational Purposes only. Thank you! 😇

**Comment by dsdanielpark** [comment]
Hello,
The Bard API package is an unofficial Python package, so we cannot provide an official Google API key. 

Please check https://github.com/dsdanielpark/Bard-API#google-palm-api for more information or reach out to Google Cloud services for an official request. As far as I know, currently, only some restricted whitelists have access to the API, so it seems like you are using this package unofficially.

Also, please refer to the Readme for sufficient information related to the Bard API package.

Thank you.
