### ISSUE TITLE
Get_answer problem

### ISSUE THREAD

**Issue by kitekun** [dsdanielpark/Bard-API#170]
File "main . py" , line 25, in get_answer
response = bard.get_answer (question)
File "/home/ runner/Bard-API/venv//lib/python
3.10/site-packages/bardapi/core. py" , line 143
, in get_answer
resp_dict = json.loads ( resp. content . split
lines( ) [3]) [O][2]
IndexError: list index out of range

It show that error when I try to get the answer

**Comment by dsdanielpark** [comment]
Please use latest version. 
```
pip install -U bardapi
```
or 
```
pip install bardapi==0.1.33
```

**Comment by kitekun** [comment]
Even that it the same error bro

**Comment by kitekun** [comment]
![Screenshot_٢٠٢٣٠٨٢١-١٧٣٠٣٨_Replit](https://github.com/dsdanielpark/Bard-API/assets/128864259/3400e02a-97b0-45d1-b1de-b6b5a2c94eea)
Look

**Comment by dsdanielpark** [comment]
Check Bard API version, and clearly reinstall package.


import bardapi

print(bardapi.__version__)

**Comment by kitekun** [comment]
I dont know bro the version is 0.1.33
I tried deleting and re-downloading the package and it was the same
