### ISSUE TITLE
Trouble creating Auto Cookie script as a cron job on github workflows

### ISSUE THREAD

**Issue by Suga7772** [dsdanielpark/Bard-API#172]
Hello , I have been working on the bard api for personal development aid and came to a hassle of having to refresh the token value.

As suggestion in the documentation there is browser_cookie3  ([documentation](https://github.com/borisbabic/browser_cookie3)) , could I get some guidance on how to work about with it?

**Comment by dsdanielpark** [comment]
The inconvenience of having to refresh tokens again recently stems from changes in Google's policies (which have been revised several times recently; the initial version did not have this inconvenience for several months). It's advisable to implement rate limiting or policy bypasses judiciously, such as using 'time.sleep(np.randint(100))' to avoid appearing to automatically request responses, but even this approach is uncertain.
