### ISSUE TITLE
Ensure the order of images in the response

### ISSUE THREAD

**Issue by kota113** [dsdanielpark/Bard-API#178]
**Solution you'd like**
I encountered this problem when I tried to match the image descriptions in the reponse and image urls.  
Since this library is converting the image urls to set, not list, the order of the urls are lost.  
  
I changed the code and the description slightly to address this issue.

**Comment by dsdanielpark** [comment]
Thank you for contribution! 

Solved at f5d8fcccc10f030310e3b4065a4fed70bdd7ae0f by [kota113](https://github.com/kota113)
