### ISSUE TITLE
Langchain integeration

### ISSUE THREAD

**Issue by Mahran-xo** [dsdanielpark/Bard-API#185]
is there any possibility that langchain works with this ?

**Comment by dsdanielpark** [comment]
Completed the task and plan to create a Pull Request. If the Pull Request is rejected, I'll provide documentation similar to Lang chain.

**Comment by drmwnrafi** [comment]
From [this documentation](https://python.langchain.com/docs/modules/model_io/models/llms/custom_llm), this code works for me:

``` import os
from bardapi import Bard
from typing import Any, List, Mapping, Optional
from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM
os.environ['_BARD_API_KEY']="xxxxxx"


class BardLLM(LLM):
    @property
    def _llm_type(self) -> str:
        return "custom"

    def _call(self, prompt: str, stop: Optional[List[str]] = None,run_manager: Optional[CallbackManagerForLLMRun] = None) -> str:
        response = Bard().get_answer(prompt)['content']
        return response

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {}

llm = BardLLM()
llm("Who are you?")

""" 
Output : I am Bard, a large language model from Google AI. I am trained on a massive dataset of text and code, and I can generate text, translate languages, write different kinds of creative content, and answer your questions in an informative way. I am still under development, but I have learned to perform many kinds of tasks, including

* I will try my best to follow your instructions and complete your requests thoughtfully.
* I will use my knowledge to answer your questions in a comprehensive and informative way, even if they are open ended, challenging, or strange.
* I will generate different creative text formats of text content, like poems, code, scripts, musical pieces, email, letters, etc. I will try my best to fulfill all your requirements.

I am excited to be able to help people with their tasks and creative projects, and I hope to learn and grow more over time.

What can I help you with today? 
"""

**Comment by dsdanielpark** [comment]
In addition to customizing it as mentioned above, I believe that submitting a PR for the variable Bard API to the official documentation is not appropriate, so I will skip this task in favor of the previous response. 

You can temporarily use the Bard API in conjunction with other methods of the Lang chain in the same way as described above.


This issue will remain open. Thank you. [drmwnrafi](https://github.com/drmwnrafi)

**Comment by andreprawira** [comment]
Does anyone know why am i getting `Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.` error when im using the code as written above, **but** its working if i do it 

```
Secure_1PSID = 'abcd'
Secure_1PSIDTS = 'defg'
chatbot = Chatbot(Secure_1PSID, Secure_1PSIDTS)

print(chatbot.ask("biggest deadlift PR"))
```

and yes, im using the same token that i use from my own code

**Comment by drmwnrafi** [comment]
> Does anyone know why am i getting `Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.` error when im using the code as written above, **but** its working if i do it
> 
> ```
> Secure_1PSID = 'abcd'
> Secure_1PSIDTS = 'defg'
> chatbot = Chatbot(Secure_1PSID, Secure_1PSIDTS)
> 
> print(chatbot.ask("biggest deadlift PR"))
> ```
> 
> and yes, im using the same token that i use from my own code

Please, read the link below :
[FAQ](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md)

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```
