### ISSUE TITLE
ask about image failed

### ISSUE THREAD

**Issue by JulioZhao97** [dsdanielpark/Bard-API#188]
💚💜 Thank you for interest. ❤️💛
Please make sure to check for more efficient package management. *Please prioritize checking existing issues first. I will repay with higher-quality code.*

**To Reproduce**
- [x] I have read [README.md](https://github.com/dsdanielpark/Bard-API). Please read me.
- [x] I have searched for existing issues. *(Most of the issues are duplicates.)*
- [x] I installed the appropriate version and confirmed that the previous version was properly removed upon reinstallation. 
- [x] I also checked the environment (not only on a single local machine but also on Google Colab, different Google accounts, and tried resetting cookies, etc. Please make sure to attempt these steps if necessary, and test the functionality in a new virtual environment if needed.)

Example
```
pip uninstall bardapi # and restart kernel
pip install bardapi==0.1.29 # check proper version
pip install -u bardapi==0.1.29 # upgrade version
```

```python
import bardapi
bardapi.__version__
```
----------Please delete the content above this line, including this line.-------------

**Version**
OS: MacOS Monterey 12.6
Python: 3.10
Bard API: 0.1.34
Using proxy: no
Legion:

**Error**
ask pure text content fine, Web-ui fine, ask image failed and give following:
```
Response Error: b\')]}\\\'\\n\\n103\\n[["er",null,null,null,null,400,null,null,null,3],["di",43],["af.httprm",42,"474965566171913227",244]]\\n25\\n[["e",4,null,null,139]]\\n\'. \nUnable to get response.\nPlease double-check the cookie values and verify your network environment or google account.
```

**Comment by Camilool8** [comment]
I am having the same issue. Also I am making sure to instantiate multi-cookies by myself and still isn't working.

(Web-UI is fine, get_answer method is fine)

**Comment by vhrehfdl** [comment]
I am having the same issue.

**Comment by Camilool8** [comment]
No updates regarding the issue?

**Comment by dsdanielpark** [comment]
[veonua](https://github.com/veonua) #189

We currently cannot support the QA for the ask_about_image method in my current region and language. We've been unsuccessful even when trying to bypass this with accounts or IPs created in other regions.

There has been an update, and I'd appreciate it if you could check why it's still not progressing.

Also, when using the same version as the previous one, did you experience the same issue? (I'm curious if it used to work and then stopped working on the same version.)

It seems that only some data types need to be changed regarding this. We would be grateful if anyone could debug this issue and submit a Pull Request.

**Comment by Camilool8** [comment]
> [veonua](https://github.com/veonua) #189
> 
> We currently cannot support the QA for the ask_about_image method in my current region and language. We've been unsuccessful even when trying to bypass this with accounts or IPs created in other regions.
> 
> There has been an update, and I'd appreciate it if you could check why it's still not progressing.
> 
> Also, when using the same version as the previous one, did you experience the same issue? (I'm curious if it used to work and then stopped working on the same version.)
> 
> It seems that only some data types need to be changed regarding this. We would be grateful if anyone could debug this issue and submit a Pull Request.

@dsdanielpark Is there any temporal solution to this issue so we could get the function working? Is kinda critical for our project to analyze some images.

**Comment by dsdanielpark** [comment]
Have you checked the installation of the GitHub version with the following command? 
```
$ pip install git+https://github.com/dsdanielpark/Bard-API.git
```

There was a recent hot fix for 'ask_about_image', but we haven't officially included it in the version as QA hasn't finished yet.

What I continue to wonder is why there's a sudden response error when it was working fine in the original version.

**Comment by dsdanielpark** [comment]
## Using 0.1.33 or 0.1.35 version for `ask_about_image` method

While wrapping some of the overall structures, version 0.1.34 could not properly support `ask_about_image` due to its omission. Please use the GitHub dev version or version 0.1.33 or 0.1.35. We apologize for the confusion. If you have any ideas for better refactoring of the structure, please feel free to contribute! Thank you.
