### ISSUE TITLE
How to continue an conversation? 

### ISSUE THREAD

**Issue by khaiphan9x** [dsdanielpark/Bard-API#19]
Can you show me what I need to save so that Bard can remember the previous conversation without starting a new one after each question?
 I'm trying to write it on PHP

 I used Chrome Dev Tools to monitor and found SNlM0e and conversation_id unchanged, I tried saving it again but the result is not as expected

**Comment by khaiphan9x** [comment]
I think it is correct to get the conversation data (conversation_id...) somewhere before get_answer

**Comment by dsdanielpark** [comment]
Trying to stick more cookie information into the session and then proceeding may be able to fix it.

Try using a `reusable session` first, then stick more cookie values ​​to the session. If you find a solution, please contribute.

**Comment by dsdanielpark** [comment]
It was confirmed that the conversation can be continued through a reusable session. Use the following code. Close the issue.

```python
from bardapi import Bard
import os
import requests

token='VwhVqhvFpnOm_sSsLszdru_DWm8otZBt3hPR9fud2BePGTk2jQmGmfcbKb_vyr3IjJFKEA.'
session = requests.Session()
session.headers = {
            "Host": "bard.google.com",
            "X-Same-Domain": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Origin": "https://bard.google.com",
            "Referer": "https://bard.google.com/",
        }
session.cookies.set("__Secure-1PSID", token)

bard = Bard(token=token, timeout=30, session=session)
bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
```

```python
bard.get_answer("What is my last prompt is?")['content']
```

**Comment by NightMachinery** [comment]
@dsdanielpark This re-usable session is the same as in the readme, correct? So one must not use sessions if one wants to reset the conversation?

Worth adding to the readme.

**Comment by dsdanielpark** [comment]
> @dsdanielpark This re-usable session is the same as in the readme, correct? So one must not use sessions if one wants to reset the conversation?
> 
> 
> 
> Worth adding to the readme.

I added a little explanation, but it doesn't mean much to continue that much conversation in the current bard. 

bardapi is just a slightly more simplified version of chatting on the bard official site. 

In practice, the very notion of continuing this conversation means that the session will be very limited and short. 

Bards don't remember me for very long, which means that I don't update parameters, just that my chat history is kept for a short period of time. 

Find out more about how the bard service works with the large language model.

**Comment by dsdanielpark** [comment]
If you keep the session fixed and test it, you can receive the last prompt of the previous conversation as part of the result. Please confirm and let me know.

If that's not the case, it would be best to maintain the conversation history and continue the conversation based on that.
