### ISSUE TITLE
AsyncClient.post() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by ser** [dsdanielpark/Bard-API#190]
It seems that documentation for httpx does not represent fully its current code. The documentation says that ```proxies``` argument to ```AsyncClient.post()``` is available but in reality it's not:

```
AsyncClient.post() got an unexpected keyword argument 'proxies'
```

After removal of ```proxies``` argument from bardapi code everything works correctly.

httpx 0.25.0

**Comment by dsdanielpark** [comment]
It will be resolved in version 0.1.39. Until then, please use the GitHub development version.
