### ISSUE TITLE
Add auto rotation cookies

### ISSUE THREAD

**Issue by Mrgaton** [dsdanielpark/Bard-API#191]
Any system to be able to auto-generate the bard cookies automatically with the Google session to be able to make the system completely autonomous

**Comment by Zyx0r** [comment]
I used browser_cookie3, I go to read the Google Chrome cookies that I opened previously, and then I can make all the calls I want without having to manually update the values.

if it gives you the permission denied error, the shortcut to the chrome executable should be modified by adding _--disable-features=LockProfileCookieDatabase_

`import browser_cookie3
session = requests.Session()

cookies = browser_cookie3.chrome(domain_name='.google.com')
PPSID = find_that_cookie(cookies, '__Secure-1PSID')
DCC = find_that_cookie(cookies, '__Secure-1PSIDCC')
DTS = find_that_cookie(cookies, '__Secure-1PSIDTS')

token = PPSID
session.cookies.set("__Secure-1PSID", PPSID)
session.cookies.set( "__Secure-1PSIDCC", DCC)
session.cookies.set("__Secure-1PSIDTS", DTS)
session.headers = SESSION_HEADERS
`

**Comment by marco99asr** [comment]
if it works;
@dsdanielpark can be an enhancement?

**Comment by dsdanielpark** [comment]
[marco99asr](https://github.com/marco99asr)
I am currently working on multiple projects, so I will conduct feature testing as time allows this weekend and proceed with updates as necessary. I appreciate the issue creation and information from [Zyx0r](https://github.com/Zyx0r). 

Also, anyone can contribute by making modifications and creating a Pull Request without having to wait. 

We always look forward to active communication and your opinions. 
Thank you.

**Comment by marco99asr** [comment]
we have to understand how client refresh tokens when they expire.
I tryed rotation of cookies but in sessions they didn't change.
Client maybe refresh token with an api but what kind of api?

**Comment by marco99asr** [comment]
using this i never saw change cookies....

my code:

`def saveCookiesNull():
    printLog("saveCookiesNull()")
    cookies = {
      "__Secure-1PSID" : "",
      "__Secure-1PSIDCC" : "",
      "__Secure-1PSIDTS" : ""
   }
   # Salva le modifiche sul disco
    with open("bardCookies.json", "w") as f:
      json.dump(cookies, f)
   

def loadCookie(cookie):  
  printLog("loadCookie(cookie)")
  try:
    with open("bardCookies.json", "r") as f:
    # Carica i dati dal file in un dizionario
      return json.load(f)[cookie]    
  except FileNotFoundError:  
    saveCookiesNull()      
    return loadCookie(cookie)
  
  
def saveCookies(cookie, value):
    printLog("saveCookies(cookie, value)")
    cookies = {}
    #leggi gli attuali
    try:
      with open("bardCookies.json", "r") as f:
        # Carica i dati dal file in un dizionario
        cookies = json.load(f)
    except FileNotFoundError:          
      saveCookiesNull()   

    cookies[cookie] = value

    # Salva le modifiche sul disco
    with open("bardCookies.json", "w") as ff:
        json.dump(cookies, ff)


def find_cookie(cookie, field, check):
     printLog("find_cookie(cookie, field)")
     for i in cookie:
         if(i.name == field):
             if i.value != check:
                printLog(field + " is different ------------------------------------------------------------------------------")
             return i.value



    PPSID   = loadCookie("__Secure-1PSID")
    DCC  = loadCookie( "__Secure-1PSIDCC")
    DTS     = loadCookie("__Secure-1PSIDTS")

    session = requests.Session()
    session.cookies.set("__Secure-1PSID", PPSID)
    session.cookies.set( "__Secure-1PSIDCC", DCC)
    session.cookies.set("__Secure-1PSIDTS", DTS)

    printLog(session.cookies)
    session.headers = SESSION_HEADERS
    bard = Bard(token=PPSID, session=session)
            input_text = ""
            
            response = bard.get_answer(input_text)

            ##Replace cookies
            PPSID = find_cookie(session.cookies, '__Secure-1PSID', PPSID)
            DCC = find_cookie(session.cookies, '__Secure-1PSIDCC', DCC)
            DTS = find_cookie(session.cookies, '__Secure-1PSIDTS', DTS)
            session.cookies.set("__Secure-1PSID", PPSID)
            session.cookies.set( "__Secure-1PSIDCC", DCC)
            session.cookies.set("__Secure-1PSIDTS", DTS)

            ##Store new cookies
            saveCookies("__Secure-1PSID", PPSID)
            saveCookies( "__Secure-1PSIDCC", DCC)
            saveCookies("__Secure-1PSIDTS", DTS)
            
            
            
            
            `

**Comment by marco99asr** [comment]
sad story im blocked by bard server:

2023-11-14 22:18:25,276 - DEBUG - https://bard.google.com:443 "GET / HTTP/1.1" 302 363
2023-11-14 22:18:25,564 - DEBUG - https://www.google.com:443 "GET /sorry/index?continue=https://bard.google.com/&q=EgSetOVNGLHkz6oGIjC__cLZI-D9CD0K9rTVy1nhmdP3S94HYepCY_nv2pRabRvl5uKAO-EMSrwn6mnXGo0yAXJaAUM HTTP/1.1" 429 3091
2023-11-14 22:18:25,565 - DEBUG - Bard Error!

**Comment by dsdanielpark** [comment]
[marco99asr](https://github.com/marco99asr)

1. Based on these two points, you may have received an HTTP 429 error. If it is determined that the requests are not from a person but from a macro or a repetitive loop, your account may be temporarily or permanently blocked.
    - Do not send requests too frequently. 
    - Do not repeatedly send the same question.

2. Consider logging out from the browser and completely closing all browsers before starting again for token refresh. Alternatively, refer to the method of resetting cookies in each browser.

The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time (rate limiting).

**Comment by Billy19191** [comment]
> Please refer to pull request #235 by [szv99](https://github.com/szv99).
> 
> We are currently working on it, and if possible, I plan to proceed with the update by the end of December.
> 
> If the update is stable, I will release it as version `0.1.39`.


That would be awesome! Cheer

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```
