### ISSUE TITLE
Bard ask_about_image method has stopped working.

### ISSUE THREAD

**Issue by noseon** [dsdanielpark/Bard-API#192]
Bard ask_about_image method has stopped working.

**Comment by arielolin** [comment]
Same for me

**Comment by dsdanielpark** [comment]
Have you checked the installation of the GitHub version with the following command? 
```
$ pip install git+https://github.com/dsdanielpark/Bard-API.git
```

There was a recent hot fix for 'ask_about_image', but we haven't officially included it in the version as QA hasn't finished yet.

What I continue to wonder is why there's a sudden response error when it was working fine in the original version.

**Comment by radu022003** [comment]
Hello I have checked the GitHub version too, ask_about_image is not working on my side either, other functions seems to work fine.

**Comment by arielolin** [comment]
@dsdanielpark  same as @radu022003,  checked the GitHub version. All other function are working as expected.

**Comment by dsdanielpark** [comment]
Can you thoroughly uninstall the package and do a clean install of bardapi version 0.1.33 to check? If the same issue arises in 0.1.33, it might be an interface change, so you might need to use a VPN. However, as mentioned, my account and region don't officially support "ask_about_image" in the UI, so it may take some time. Thank you.

**Comment by jtenman** [comment]
Version 0.1.33 works. Originally had 0.1.34 installed, but downgrading fixes the problem.

**Comment by arielolin** [comment]
thanks a lot!

**Comment by dsdanielpark** [comment]
## Using 0.1.33 or 0.1.35 version for `ask_about_image` method

While wrapping some of the overall structures, version 0.1.34 could not properly support `ask_about_image` due to its omission. Please use the GitHub dev version or version 0.1.33 or 0.1.35. We apologize for the confusion. If you have any ideas for better refactoring of the structure, please feel free to contribute! Thank you.

**Comment by shaggy2626** [comment]
When you say ask about an image are you referring to this  https://console.cloud.google.com/vertex-ai/generative/vision? Or actually uploading an image from the Bard UI

**Comment by n2nco** [comment]
RE: ask about image (in both v0.1.33 & v0.1.35) 

I get the following error when calling ask about image in a fastapi context:

 `'Response Error: b\')]}\\\'\\n\\n39\\n[["wrb.fr",null,null,null,null,[13]]]\\n57\\n[["di",855],["af.httprm",854,"6152747459826333784",11]]\\n25\\n[["e",4,null,null,133]]\\n\'. \nUnable to get response.\nPlease double-check the cookie values and verify your network environment or google account.'` 
 
But it returns successfully when running as a standalone file

Any tips here?  

My debugger state at the call site: (still returns 200)

![image](https://github.com/dsdanielpark/Bard-API/assets/36323943/f467b236-c298-4f3f-a275-2336d7082298)

fast api:
![image](https://github.com/dsdanielpark/Bard-API/assets/36323943/08297f53-a214-4b59-a449-d4d9119466a2)

single file: (correct content in response)
![image](https://github.com/dsdanielpark/Bard-API/assets/36323943/6e4d5f00-d230-46fd-b111-b4e365f91c81)
