### ISSUE TITLE
return answer in chunks

### ISSUE THREAD

**Issue by themw123** [dsdanielpark/Bard-API#193]
Is it possible to return the answer of bard in chunks? I would like to stream/return the text chunks as they are generated. I was trying to do it with async but i am not sure if async is the right way for it.

**Comment by themw123** [comment]
Yes sorry. I meant if it is possible to get the text that is returned not as a whole but as individual parts so that you don't have to wait so long for an answer. For example chatgpt does it this way, there the text is generated step by step and returned. the advantage is that you then have a shorter delay if you want to have the answer read out by bard. 
`bard.get_answer("Who are you")['content'] `
would have to return the answer in individual parts, so you don't have to wait until everything is generated.

**Comment by dsdanielpark** [comment]
I understand now. You're talking about the process where responses are generated gradually. In the case of the Hugging Face model I'm working on, I can adjust it in that way or make it more autonomous, but it's currently challenging to implement such features through the API. Additionally, Bard is not a specialized text generation model; it's a multi-modality generative AI with various experimental elements, so while providing services in that manner might be possible, I believe there's a high chance it won't be supported.
