### ISSUE TITLE
license??

### ISSUE THREAD

**Issue by lihkinVerma** [dsdanielpark/Bard-API#2]
What is the license to use this repository? Apache, MIT or GPL, Please upload

**Comment by dsdanielpark** [comment]
- [MIT](https://opensource.org/license/mit/) 
- Belongs to Google AI's Bard license. 
- The code is licensed under the MIT License.
- But retained under Google Bard's license policy in the future.
- The author is not involved in legal responsibility, please refer to the bottom of the readme.
