### ISSUE TITLE
Is google bard has limit number of question?

### ISSUE THREAD

**Issue by sonygod** [dsdanielpark/Bard-API#20]
It appears that there's a quota limitation when invoking the Bard API. I've written a loop for the calls, and I've noticed there seems to be a cap on the number of requests. Once a certain threshold is reached, it starts to return errors, preventing further queries.

**Comment by sonygod** [comment]
it's seem there is rate-limits like  gpt 

many guys had this issue ,May be you need to add this note to readme.md.

https://www.reddit.com/r/Bard/comments/11y5wof/thats_all_bard_can_answer_right_now_its/

**Comment by sonygod** [comment]
<img width="925" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/748320/d8ce756a-9439-4481-acd5-ac1868da1f31">


Yes, there are some limits on how you can use Google Bard. For example, you can only ask a certain number of questions in a given period of time. If you exceed this limit, your account may be temporarily blocked.

The specific limits vary depending on how you are using Google Bard. For example, if you are using Google Bard through the web interface, you can ask up to 200 questions per hour. If you are using Google Bard through the API, you can ask up to 1000 questions per hour.

If you are using Google Bard for a legitimate purpose, such as research or education, you can request an increase in your limit. To do this, please contact Google support.

Here are some of the limits on using Google Bard:

You can only ask a certain number of questions in a given period of time.
You can only ask questions that are relevant to the topic at hand.
You cannot ask questions that are offensive or harmful.
You cannot ask questions that are intended to spam or abuse the system.
If you violate any of these limits, your account may be temporarily blocked. If you are blocked, you will not be able to use Google Bard until the block is lifted.

Google Bard is still under development, and we are working to improve it. We appreciate your patience and understanding as we work to make Google Bard the best it can be.

**Comment by NormTurtle** [comment]
![image](https://github.com/dsdanielpark/Bard-API/assets/108952834/3fbaa7a4-7e8f-4d6a-999d-dae4d4f90cea)
i dont get it ? 

do we still have to pay using this repo?

**Comment by connorv001** [comment]
> ![image](https://user-images.githubusercontent.com/108952834/239707235-3fbaa7a4-7e8f-4d6a-999d-dae4d4f90cea.png) i dont get it ?
> 
> do we still have to pay using this repo?

No.

**Comment by NormTurtle** [comment]
GOOD
