### ISSUE TITLE
 bard.ask_about_image to support session

### ISSUE THREAD

**Issue by arielolin** [dsdanielpark/Bard-API#204]
The `bard.ask_about_image method`, when used with the session argument, initializes a new conversation with each invocation. would be great if it was aligned with  `bard.get_answer`

**Comment by dsdanielpark** [comment]
The API endpoint for image uploads may be different, so we're not sure if it will work, but we'll try a few methods. This will be done experimentally in the GitHub dev version. (Target modification date: 2023-10-17)

**Comment by dsdanielpark** [comment]
After checking the code, I found that the package doesn't establish a new session every time. 

However, after uploading an image, another AI model (the image encoder model) needs to process the data so that Bard can interpret the image as text. As a result, it might appear as if a new session is being opened when Bard updates parameters internally with the text results.

Therefore, this behavior cannot be modified at the package level, and it's not possible to make changes to the 'ask_about_method' API architecture.


However, it is possible to attempt to fixate the session through the following code.
```python
from bardapi import Bard
import os
import requests
token='xxxxxxx'

session = requests.Session()
session.headers = {
            "Host": "bard.google.com",
            "X-Same-Domain": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Origin": "https://bard.google.com",
            "Referer": "https://bard.google.com/",
        }
session.cookies.set("__Secure-1PSID", token) 

bard = Bard(token=token, session=session, timeout=30)
bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']

# ask about image method
image = open('image.jpg', 'rb').read() # (jpeg, png, webp) are supported.
bard_answer = bard.ask_about_image('What is in the image?', image)
```

**Comment by veonua** [comment]
to get both methods aligned I created another method that works with text, images, and tools

bard_answer = bard.ask('What is in the image?', image:bytes, image_name:str )

**Comment by azhardegr8** [comment]
I am getting below error while using ask_about_image, I am sending jpg image but still getting error

{'content': 'Response Error: b\')]}\\\'\\n\\n39\\n[["wrb.fr",null,null,null,null             ,[13]]]\\n57\\n[["di",473],["af.httprm",473,"-4968525896118123017",9]]\\n25\\n[[             "e",4,null,null,133]]\\n\'. \nUnable to get response.\nPlease double-check the c             ookie values and verify your network environment or google account.'}

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```
