### ISSUE TITLE
Getting weird error response while executing simple script

### ISSUE THREAD

**Issue by rudrajyotibhattacharya** [dsdanielpark/Bard-API#21]
from bardapi import Bard

token = '.......'
bard = Bard(token=token)
resp = bard.get_answer("What is BARD?")

print(resp)

It responds with **{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["[wrb.fr](http://wrb.fr/)",null,null,null,null,[9]]]\\n55\\n[["di",72],["af.httprm",72,"8367677104245371628",47]]\\n25\\n[["e",4,null,null,130]]\\n\'.'}**

I started trying the API today morning.. Anyone else facing such issue or am I making a newbie mistake?

**Comment by rudrajyotibhattacharya** [comment]
I am based in India. Is it due to country? I tried with VPN but got the same result..

**Comment by dsdanielpark** [comment]
Please refer to the following [answer](https://github.com/dsdanielpark/Bard-API/issues/1#issuecomment-1547009609) for instructions. 

I've also found that the same error sometimes occurs during normal processes. Please give it some time or try resetting your cookie values.

Close this issue as a duplicate issue.

**Comment by rudrajyotibhattacharya** [comment]
Thanks. I will try the options. Closing the issue for the moment..
