### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by LcfherShell** [dsdanielpark/Bard-API#211]
I am using python version 3.8.10, and I get the following error code:

bardapi\models\tools\flight.py", line 71, in BardFlightContent
    def flights(self) -> list[BardFlight]:
TypeError: 'type' object is not subscriptable

Can you help me

**Comment by YemiReble** [comment]
Upgrade the package. Upgrading it fixed this error for me. 
Use: pip install --upgrade bardapi==0.1.29

**Comment by dsdanielpark** [comment]
The issues related to type hints occurred in versions 0.1.36 and 0.1.37. Please refrain from using those versions. For more details, please refer to the release notes at https://github.com/dsdanielpark/Bard-API/releases.
