### ISSUE TITLE
AsyncClient.get() got an unexpected keyword argument 'follow_redirects

### ISSUE THREAD

**Issue by odgtr** [dsdanielpark/Bard-API#213]
```
async def generate_response(user_prompt):
    response = await bard.get_answer(user_prompt)
    return response
```
this was working until yesterday, until this error appeared randomly:
```
AsyncClient.get() got an unexpected keyword argument 'follow_redirects'
```

**Comment by dsdanielpark** [comment]
Hello,

Could you please check the package version with bardapi.version? If you're encountering repetitive errors in the same code, it's possible that the Python kernel has changed, or it may not be working within a fixed environment, possibly inside a virtual environment.

**Comment by dsdanielpark** [comment]
Additionally, this issue is also a problem in some package versions and has been resolved, so we are closing this issue. Please feel free to reopen it if the problem recurs. (If you could provide information about the package version in the comments, we would appreciate it.)
