### ISSUE TITLE
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

### ISSUE THREAD

**Issue by marl0nx** [dsdanielpark/Bard-API#217]
CONSENT
SOCS
APISID
HSID
SAPISID
SID
SSID
__Secure-1PAPISID
__Secure-1PSID
__Secure-3PAPISID
__Secure-3PSID
SEARCH_SAMESITE
1P_JAR
__Secure-1PSIDTS
__Secure-3PSIDTS
AEC
NID
SIDCC
__Secure-1PSIDCC
__Secure-3PSIDCC
SNID
ACCOUNT_CHOOSER
LSOLH
LSID
__Host-1PLSID
__Host-3PLSID
__Host-GAPS
OSID
__Secure-OSID
_ga
_ga_Q3KJSFNQDY
_GRECAPTCHA
OTZ
DV
OTZ
CONSENT
SOCS
NID
HSID
SSID
APISID
SAPISID
__Secure-1PAPISID
__Secure-3PAPISID
SID
__Secure-1PSID
__Secure-3PSID
OGPC
SEARCH_SAMESITE
AEC
1P_JAR
__Secure-1PSIDTS
__Secure-3PSIDTS
SIDCC
__Secure-1PSIDCC
__Secure-3PSIDCC
TAID
AID
SNID
ACCOUNT_CHOOSER
LSID
__Host-1PLSID
__Host-3PLSID
__Host-GAPS
_GRECAPTCHA
OTZ
DV
OTZ
__Host-GMAIL_SCH_GMN
__Host-GMAIL_SCH_GMS
__Host-GMAIL_SCH_GML
OSID
__Secure-OSID
COMPASS
COMPASS
COMPASS
OTZ
OTZ
OSID
__Secure-OSID
_ga
_ga_H30R9PNQFN
COMPASS
_ga
_ga_S3V05QCXK5
{'__Secure-1PSID': 'MY COOKIE WAS HERE. I REPLACED IT TO NOT LEAK IT'}
Traceback (most recent call last):
  File "C:\Users\mdevp\PycharmProjects\OSINTDatabaseV1\test.py", line 3, in <module>
    bard = Bard(token_from_browser=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mdevp\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mdevp\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 154, in _get_snim0e
    raise Exception(
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

Process finished with exit code 1

Code:
```
from bardapi import Bard

bard = Bard(token_from_browser=True)
res = bard.get_answer('Wie ist das Wetter in Berlin?')
print(res)
```

**Comment by requizm** [comment]
#155

**Comment by dsdanielpark** [comment]
duplicated issue. refer to #155
