### ISSUE TITLE
ModuleNotFoundError: No module named 'bardapi'

### ISSUE THREAD

**Issue by samedovzaur** [dsdanielpark/Bard-API#22]
![Screenshot 2023-05-19 at 21 14 29](https://github.com/dsdanielpark/Bard-API/assets/101812544/44bcc795-c488-42fb-b82f-e7dbd65c9028)

it doesn't work, i've downgraded the python version for whisper but it doesn't work with thi api. I don't know why?

**Comment by dsdanielpark** [comment]
If you're experiencing issues with the installation of the bardapi package in your current Python interpreter environment, you can try the following steps:

If you are using ipython and want to install bardapi, you can execute the following command in a separate shell or terminal window: pip install bardapi.

If you are using a virtual environment, make sure you activate the virtual environment and then install bardapi within it. You can use the command: pip install bardapi.

The issue you're facing is not directly related to Python version compatibility but rather an installation issue with the package. If you have any further questions or need additional assistance, feel free to ask. 

Thank you!
