### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SouravApiDev** [dsdanielpark/Bard-API#221]
Exception Traceback (most recent call last)
in <cell line: 5>()
3 os.environ['_BARD_API_KEY']="epiIk6A2qHAOPEfJcjRfpd6L-8ZZVMQOpkSK6HrN-J1qASFreTknUC2GIh3QC8LWQpHpwg."
4
----> 5 Bard().get_answer("what is pi?")['content']

[/usr/local/lib/python3.10/dist-packages/bardapi/core.py](https://localhost:8080/#) in _get_snim0e(self)
    152         snim0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text)
    153         if not snim0e:
--> 154             raise Exception(
    155                 "SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'."
    156             )

Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

**Comment by dsdanielpark** [comment]
#128, #155

Please, Read this FAQ page very carefully. https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md
