### ISSUE TITLE
Is it possible to use this one a headless server?

### ISSUE THREAD

**Issue by mathisen99** [dsdanielpark/Bard-API#222]
Hello!
i know we need to get the "token" from our cookies in the browser, and i know it is computer specfic.
So! my question is, have anyone figured out a way to use this on a headless server where there is no GUI at all ?
or is there any way to go around this that i missed?

Thanks!

**Comment by veonua** [comment]
Yes, almost. I have it working in my telegram bot. But somehow Google detected I was left to vacation and got my token expired. 
I won't be able to recreate the token even when I VPNed to that network.

**Comment by mathisen99** [comment]
got it working by just using the token from a diffrent computer i thought they where computer specific.
