### ISSUE TITLE
{'content': 'Response Error: b\')]}\\\'\\n\\n39\\n[["wrb.fr",null,null,null,null,[13]]]\\n60\\n[["di",6961],

### ISSUE THREAD

**Issue by mdatiqmazumder** [dsdanielpark/Bard-API#226]
{'content': 'Response Error: b\')]}\\\'\\n\\n39\\n[["wrb.fr",null,null,null,null,[13]]]\\n60\\n[["di",6961],["af.httprm",6961,"-5783011263836368843",37]]\\n25\\n[["e",4,null,null,136]]\\n\'. \nTemporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.'}

**Comment by dsdanielpark** [comment]
Please, read  carefully [FAQ](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md) and Isuue #128
