### ISSUE TITLE
Exception: No supported brower found or issue with cookie extraction

### ISSUE THREAD

**Issue by luoysuan** [dsdanielpark/Bard-API#227]
**Version**
OS:win10
Python:3.11
Bard API:0.1.38

**error**
auto cookie error
![image](https://github.com/dsdanielpark/Bard-API/assets/51365362/05eacc43-b3af-4d44-94a6-bd5220bbe4d6)

**Comment by luoysuan** [comment]
bard I have logged in.

**Comment by dsdanielpark** [comment]
As written on GitHub, the auto cookie bard can be unstable and may not work. 

1. try explicitly declaring a token to the normal bard and see if it can return normally.
2. then reset your browser, etc., and try running the code with the BARD's WEB UI enabled in your browser. Naturally, all of these machines should be on the same OS. 
3. For more information and issues, try the issue page for brower_cookie3.

Read on for the next auto cookie bard and take note.
Using [browser_cookie3](https://github.com/borisbabic/browser_cookie3) we extract the `__Secure-1PSID` cookie from all browsers, and then we can use the API without passing the token. However, there are still incomplete dependency packages and various variables, so please seek assistance in the following [GitHub Issues](https://github.com/borisbabic/browser_cookie3/issues) or adjust your browser's version.
- Visit https://bard.google.com/ in your browser and execute the following command while in the chat-enabled state. Refer to browser_cookie3 for details on how it works. If any issues arise, please restart the browser or log in to your Google account again. 
*Recommended to keep the browser open.*

**Comment by luoysuan** [comment]
> As written on GitHub, the auto cookie bard can be unstable and may not work.正如 GitHub 上所写，自动 cookie bard 可能不稳定并且可能无法工作。
> 
> 1. try explicitly declaring a token to the normal bard and see if it can return normally.尝试向普通吟游诗人明确声明一个令牌，看看它是否可以正常返回。
> 2. then reset your browser, etc., and try running the code with the BARD's WEB UI enabled in your browser. Naturally, all of these machines should be on the same OS.然后重置浏览器等，并尝试在浏览器中启用 BARD WEB UI 的情况下运行代码。当然，所有这些机器都应该运行在相同的操作系统上。
> 3. For more information and issues, try the issue page for brower_cookie3.有关更多信息和问题，请尝试 browser_cookie3 的问题页面。
> 
> Read on for the next auto cookie bard and take note.继续阅读下一篇自动饼干吟游诗人并记下。 Using [browser_cookie3](https://github.com/borisbabic/browser_cookie3) we extract the `__Secure-1PSID` cookie from all browsers, and then we can use the API without passing the token. However, there are still incomplete dependency packages and various variables, so please seek assistance in the following [GitHub Issues](https://github.com/borisbabic/browser_cookie3/issues) or adjust your browser's version. 使用 browser_cookie3，我们从所有浏览器中提取 `__Secure-1PSID` cookie，然后我们可以在不传递令牌的情况下使用 API。但仍然存在不完整的依赖包和各种变量，因此请在以下 GitHub Issues 中寻求帮助或调整浏览器版本。
> 
> * Visit https://bard.google.com/ in your browser and execute the following command while in the chat-enabled state. Refer to browser_cookie3 for details on how it works. If any issues arise, please restart the browser or log in to your Google account again.在浏览器中访问 https://bard.google.com/ 并在启用聊天状态下执行以下命令。有关其工作原理的详细信息，请参阅 browser_cookie3。如果出现任何问题，请重新启动浏览器或重新登录您的Google帐户。
>   _Recommended to keep the browser open.建议保持浏览器打开。_

I was able to use it by adding the --disable-features=LockProfileCookieDatabase parameter to the browser, but now it returns 404.

![image](https://github.com/dsdanielpark/Bard-API/assets/51365362/8a3384e0-6469-449b-8d1a-b3084a03e740)
