### ISSUE TITLE
SNlM0e : Refresh automatically

### ISSUE THREAD

**Issue by thekidchad** [dsdanielpark/Bard-API#231]
Hi,
Sometimes, if you make several requests by using the session cookie, the SNlM0e is not longer displayed if you make an HTTP request to https://bard.google.com with the session cookie.
Then you need to manually to bard.google.com and refresh the cookie.
Has anyone found a solution to automatically fix the non displayable SNlM0e in the content of bard.google.com without a human action ? (I already use a proxy)

**Comment by bluemods** [comment]
I made a client that does this (currently private). It refreshes automatically in the background using the https://accounts.google.com/RotateCookies endpoint. People looking to implement this should look for requests to accounts.google.com to rotate the cookies. Doing so keeps the session alive indefinitely.

**Comment by ponomkir42** [comment]
> I made a client that does this (currently private). It refreshes automatically in the background in 10-15 minute intervals using the https://accounts.google.com/RotateCookies endpoint. People looking to implement this should look for requests to accounts.google.com to rotate the cookies. Doing so keeps the session alive indefinitely.

hi! can you provide some example request to this endpoint?

**Comment by memo11264** [comment]
Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

**Comment by davzer27** [comment]
@bluemods Yes i have seen this query to get the new cookies but how do you do if the account is flagged ? 
fyi : 

`curl --location 'https://accounts.google.com/RotateCookiesPage?og_pid=000&rot=1&origin=https%3A%2F%2Fbard.google.com&exp_id=0000' \
--header 'authority: accounts.google.com' \
--header 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
--header 'cookie: YOUR COOKIE'`

and then you get the new cookies.
But I tried with a session that has already "the SNIM0e not found" and I received a 401 status code.

So when do you refresh the cookie ? Do you do before it flag ?

**Comment by bluemods** [comment]
@davzer27 you must rotate the cookies before they become invalid. They become invalid automatically if you leave the Bard tab that you got the cookies from open, because the browser will rotate the cookies at some point which invalidates the old ones.

So you need to do this:
- On your browser, open a tab with Bard
- Wait for a request to accounts.google.com to appear in the network tab
- Copy the cookie header and use the cookies for subsequent Bard requests
- Rotate the cookies every 10-15 mins or so

In my use, cookies never expire when this is done. It's best to log in using a fresh window, since rotating the cookies invalidates the session on the browser and logs you out (the Bard client takes control of the session)

If you know Kotlin, maybe the attached file can help you (rename .zip to .kt to open it)

[AuthToken.zip](https://github.com/dsdanielpark/Bard-API/files/13401489/AuthToken.zip)

**Comment by davzer27** [comment]
Oh you mean if you use a fresh window (private navigation for example), no need to rotate the cookie ? 
This thing is really random @bluemods 
Thank you so much

**Comment by lyesbenacer** [comment]
Do you think it would be possible to run the program without having to put the cookies ourselves ? I took a look at the Kotlin file and it feels like it retrieves the cookies by accesing the content of the `https://bard.google.com/chat?hl=en` html page.

If the right Html provided, it can parse it and then rotate the tokens everytimes it expires, right ?

**Comment by rezaxanii** [comment]
Hello, when I use this code, I get this error:
```
<html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 401 (Bad Request)!!1</title><style nonce="GE6VHQU3NnHOqwAY2jYzTg">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><main id="af-error-container" role="main"><a href=//www.google.com><span id=logo aria-label=Google role=img></span></a><p><b>401.</b> <ins>That’s an error.</ins><p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins></main>curl: (3) URL rejected: Malformed input to a URL function          curl: (3) URL rejected: Malformed input to a URL function
curl: (3) URL rejected: Malformed input to a URL function
curl: (3) URL rejected: Malformed input to a URL function
curl: (3) URL rejected: Malformed input to a URL function                   curl: (3) URL rejected: Malformed input to a URL function
```

(When I did this the code was valid)

**Comment by tinker1234** [comment]
i use selenium to grab the new cookie it doesn't work in headless mode and you have to point to a profile that already is logged in because google blocks selenium from logging in

**Comment by tinker1234** [comment]
```python
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep

class Browser():
    def __init__(self, headless=False):
        self.options = Options()
        if headless:
            self.options.add_argument("--headless")
            self.options.headless = True
        self.options.add_experimental_option("detach", True)
        self.options.add_argument("user-data-dir=C:\\Users\\USER HERE\\AppData\\Local\\Google\\Chrome\\User Data")
        self.driver = webdriver.Chrome(options=self.options, service=Service(ChromeDriverManager().install()))

    def get_cookie(self, url='https://bard.google.com'):
        self.driver.get(url)
        sleep(3)
        all_cookies=self.driver.get_cookies()
        cookies_dict = {}
        for cookie in all_cookies:
            cookies_dict[cookie['name']] = cookie['value']
        self.close()
        return cookies_dict

    def close(self):
        self.driver.quit()
```

**Comment by bluemods** [comment]
Using a chrome web driver just to retrieve cookies is overkill, just copy the headers from a chrome browser and do it yourself

**Comment by SetoKaiba** [comment]
Sometimes the cookie from the browser is not changed. But the python can't get SNlm0e.

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
