### ISSUE TITLE
Does this API use the new Gemini Pro model, instead of PaLM2?

### ISSUE THREAD

**Issue by hansfzlorenzana** [dsdanielpark/Bard-API#243]
**Solution you'd like**
- Please confirm if this API uses the Gemini Pro model instead of PaLM2
- If so, include Gemini Pro on the READMEs or docs

Thanks!

**Comment by kaizenjinco** [comment]
IMO, because this project base on the response from the website of Google Bard. Google may limited some functions or features in your region like Gemini Pro and Ultra only works with English (unofficial news). So depend on your region and website :D

**Comment by dsdanielpark** [comment]
Please check out #262
