### ISSUE TITLE
407 Proxy Authentication Required

### ISSUE THREAD

**Issue by plsgivemeachane** [dsdanielpark/Bard-API#245]
**Describe the bug**
The bug cause when using smart proxy to bard because my location waasn't matched

**Version**
OS: Window 11
Python: 3.10.13
Bard API: Latest
Using proxy: Smart Proxy
Legion: <Not included>

**Code**
```python
# ... Import thing ...
proxy_url = "http://xxxxxxxxx@smartproxy.crawlbase.com:8012" 
proxies = {"http": proxy_url, "https": proxy_url}
newSessions = requests.Session()
# ... Some other code ...
newSessions.headers = SESSION_HEADERS
newSessions.cookies.set("__Secure-3PSID", token)
bard = Bard(token=token, session=newSessions, proxies=proxies)
answer = bard.get_answer(prompt)['content']
```

**Error**
```
HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to
connect to proxy', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
```

**Comment by dsdanielpark** [comment]
[Hamza-Ikhlaq](https://github.com/Hamza-Ikhlaq) might be able to help you. 

This is not an issue or error that can be resolved at the package level.

**Comment by dsdanielpark** [comment]
This issue is a difficult problem to address at the package level, so it might be better to seek help from [crawlbase](https://crawlbase.com/).

Therefore, I am closing this issue. Thank you.
