### ISSUE TITLE
Bard is now upgraded to Gemini Pro in English, and extensions in Bard is now available. So how can I use it in this API?

### ISSUE THREAD

**Issue by eienmojiki206** [dsdanielpark/Bard-API#246]

**Comment by dsdanielpark** [comment]
# Access to Gemini Pro in English is Available Only on Bard

The current BardAPI is a simple REST API format that allows receiving the same responses as the [Bard Web UI](https://bard.google.com/chat). Therefore, if you can receive answers from Gemini Pro on the web UI, BardAPI can also return answers from Gemini similarly.
- However, this is not an official API, and currently, there are no official early access or waiting lists, as we have conducted beta testing with a few reliable experts.
- Bard API package is not an official API.
- There is Google's official PaLM2 API, but it also does not provide identical responses to Bard (in some aspects, Bard is superior).
- Currently, responses from Gemini and previous versions of models are being provided simultaneously.
- There is some support for extensions of BardAPI, but they do not function perfectly.
- It may operate differently based on region, account, etc., and separate handling is necessary for using proxies, etc.
- Please read the [FAQ](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md).

For more details, refer to Gemini's official documentation.
Gmini Introduction: https://deepmind.google/technologies/gemini/#introduction
Related links:
- https://developers.googleblog.com/2023/12/how-its-made-gemini-multimodal-prompting.html
- https://www.youtube.com/watch?v=UIZAiXYceBI
- As the bard says ... 
- <img width="479" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/81407603/321f4fdc-9422-41f9-a296-f090a543d3db">

**Comment by dsdanielpark** [comment]
As others may also be curious, I will keep this issue open until January.

However, as the situation is constantly changing, the content of this response may vary. In case of any changes, I will update the readme, so I would sincerely appreciate it if you could thoroughly read the readme.

**Comment by dsdanielpark** [comment]
#262
