### ISSUE TITLE
How do I use cookies with ChatBard

### ISSUE THREAD

**Issue by tinker1234** [dsdanielpark/Bard-API#250]
i can only use bard with full cookie dict

**Comment by xtsea** [comment]
> i can only use bard with full cookie dict

https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard

**Comment by dsdanielpark** [comment]
Most of the content can be checked through the following example. Thank you.

- [Colab Examples](https://colab.research.google.com/drive/1zzzlTIh0kt2MdjLzvXRby1rWbHzmog8t?usp=sharing#scrollTo=2jNwACIl05yi)
 - [Additional Documents for developers](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_DEV.md#multi-cookie-bard)
- [FAQ](https://github.com/dsdanielpark/Bard-API/blob/main/documents/README_FAQ.md)
