### ISSUE TITLE
My __Secure-1PSID is a long string starting with "g." instead of a string ending with dot "."

### ISSUE THREAD

**Issue by g-jing** [dsdanielpark/Bard-API#261]
My __Secure-1PSID is a long string starting with "g." instead of a string ending with dot "." Anyone could help on this issue?

**Comment by sanduvasilebogdan** [comment]
try in other browser, like chrome

**Comment by plessbd** [comment]
I am also running into this issue

**Comment by dsdanielpark** [comment]
[g-jing](https://github.com/g-jing), [plessbd](https://github.com/plessbd)

Could you please let me know the Country, Region, and Language associated with your account?

**Comment by plessbd** [comment]
> [g-jing](https://github.com/g-jing), [plessbd](https://github.com/plessbd)
> 
> Could you please let me know the `Country`, `Region`, and `Language` associated with your account?
> 
> And after logging out of the account, closing the browser, and then reopening the browser to log in again, did you check the new cookie value?

Not 100% sure how to check those, but I am in NY, USA and using English.

Yes, sign out, clear browser cache and cookies, close, and reopen using private window, both firefox and chrome

**Comment by JO-JO-Lin** [comment]
Excuse, this problem has fixed?

**Comment by dsdanielpark** [comment]
This issue has been resolved in bardapi version 0.1.39. Instead of raising errors using assert, the code has been updated to provide guidance to users through print statements, as most users have cookie values ending with a single dot. Thank you for reporting the issue.

## Bard API - version 0.1.39

```
$ pip install bardapi==0.1.39
```
```
$ pip install -q -U bardapi
```
