### ISSUE TITLE
Bard __SECURE-1PSID does not match

### ISSUE THREAD

**Issue by odgtr** [dsdanielpark/Bard-API#269]
Hi, i'm encountering this issue where I'm pressing F12, going into cookies and bard, than my __SECURE-1PSID is just weird characters. it doesn't even include a dot at the end.

Here's what it looks like (middle part is censored) - g.a000fghkDGuKkDhA7ZG2aOHPl8eS6JPgxwXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX19UgRoVAUF8yKoTfj46F5jgzNp9WaAFST4P0076

I've tried logging off and logging on again, tried switching accounts/browsers/network but none worked. my token is in this weird character format. What can I do to get my old token format back?

**Comment by dsdanielpark** [comment]
The errors from similar users have been reported, so starting from version 0.1.39, we have changed "assrt" to "print" in order to allow receiving cookie values that do not end with a single dot.

We are still unsure if any rules regarding cookie values for users from any specific country or region have been altered.

If bardapi does not function properly with the mentioned cookie value, please try confirming with three or more different cookie values using multi-cookie or similar methods and kindly report the issues. Thank you.


#261

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```
