### ISSUE TITLE
Google renames its chatbot Bard to Gemini

### ISSUE THREAD

**Issue by aniruddhkrish** [dsdanielpark/Bard-API#275]
Recently, it came to my notice that Google has rebranded Bard as Gemini. Will it affect your unofficial API?

**Comment by OlegRuban-ai** [comment]
as for me, this doesn't work now, according to the code all requests go to bard.google.com and are not sent to gemini.google.com

**Comment by FriedaMarvin** [comment]
Just tried it out, got this error
Response status code is not 200. Response Status is 429

**Comment by aniruddhkrish** [comment]
I am also receiving errors.

**Comment by bluemods** [comment]
Change all references of `bard.google.com` to `gemini.google.com` and you should be back in business.

**Comment by zabeiua** [comment]
> Change all references of `bard.google.com` to `gemini.google.com` in your code and you should be back in business.

This should do the developer, i suppose. We, users, are waiting to `pip install -U bardapi`

**Comment by irfanbd2** [comment]
1.Change in core "https://bard.google.com/" **TO** "https://gemini.google.com/app"
2.Make sure to pass two cookie **NID** and **GOOGLE_ABUSE_EXEMPTION** This two are main cookie

That's it then It will work perfectly

**Comment by irfanbd2** [comment]
1.Change in core_cookies.py  "https://bard.google.com/" TO "https://gemini.google.com/app" and change in core.py bard.google to gemini.google

2.Make sure to pass four cookie __Secure-1PSID, __Secure-1PSIDTS,NID and GOOGLE_ABUSE_EXEMPTION This four are main cookie

and change _get_session to 

    def _get_session(self, session: Optional[requests.Session]) -> requests.Session:
        """
        Get the requests Session object.

        Args:
            session (requests.Session): Requests session object.

        Returns:
            requests.Session: The Session object.
        """

        if session is None:
            new_session = requests.Session()
            cookie = ""
            for k, v in self.cookie_dict.items():
                cookie += f"{k}={v}; "
            new_session.headers.update({"Cookie": cookie})
            return new_session
        else:
            return session


That's it then It will work perfectly

**Comment by sambitweeting** [comment]
When we can expect a update from developer? So that we update the current API.

**Comment by aniruddhkrish** [comment]
Thank you for your solutions. I will try it ASAP.

**Comment by aniruddhkrish** [comment]
> > Change all references of `bard.google.com` to `gemini.google.com` in your code and you should be back in business.
> 
> This should do the developer, i suppose. We, users, are waiting to `pip install -U bardapi`

Exactly correct. The developer should do it.

**Comment by FriedaMarvin** [comment]
@irfanbd2 where can i find those files? can you give the general file path for those files?
Thanks

**Comment by aniruddhkrish** [comment]
@irfanbd2

Thank you for your solution. Only one thing to update when you create the session headers, I mean user agent, you have to change the host from bard.google.com to gemini.google.com. I did it and is working for me. Thank you once again. 
![Screenshot 2024-02-09 200555](https://github.com/dsdanielpark/Bard-API/assets/159460620/b74c5dae-a703-4b16-8a19-8c228142c2f6)

**Comment by aniruddhkrish** [comment]
@FriedaMarvin 

Please find the updated files 
[Updated files.zip](https://github.com/dsdanielpark/Bard-API/files/14223020/Updated.files.zip)

Unzip and paste the files in the appropriate folder. 

For any assistance, don't hesitate to comment here.

**Comment by jacktse0225** [comment]
@aniruddhkrish 
I put the files in the folder already. But I still got the error: requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by eienmojiki206** [comment]
> @aniruddhkrish I put the files in the folder already. But I still got the error: requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

You can try changing `"/app"`  to `"/"` in Referer of the sessions. It works good for me

**Comment by aniruddhkrish** [comment]
> @aniruddhkrish I put the files in the folder already. But I still got the error: requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

Did you change the session headers?

**Comment by Goodday777** [comment]
Previously, if there was only __Secure-1PSID,
If authentication was possible
For now, if you don't have __Secure-1PSIDTS (expiring or changing soon)
It doesn't give at.
Also, in some environments
If GOOGLE_ABUSE_EXEMPTION is not present, access itself is denied.

As we moved from Bard to Gemini, it became difficult to use this function with just the __Secure-1PSID value.

I am of the opinion that it will become difficult in the future if there is no function to automatically update the __Secure-1PSIDTS (expiring or changing soon) value.

**Comment by aniruddhkrish** [comment]
@Goodday777 

I have found the solution for this. 

But I think this only works with Firefox browser. 

Here are the steps to use the latest Gemini AI through Bardapi with some kind of stability. 

Install Firefox. 

Sign in to Gemini (formerly Bard) with your google account credentials. 

Unzip the updated files and place it in the appropriate folders (If you find any issues comment here). 

Then you will be able to use bardapi seamlessly with the following code. 

```python
import requests
from bardapi import SESSION_HEADERS, BardCookies
import browser_cookie3

domain = '.google.com'

firefox_cookies = browser_cookie3.firefox(domain_name=domain)

psid = '__Secure-1PSID'
dts = '__Secure-1PSIDTS'
dcc = '__Secure-1PSIDCC'
nid = 'NID'

psid_value = None
dts_value = None
dcc_value = None
nid_value = None

for cookie in firefox_cookies:
    if cookie.name == psid:
        psid_value = cookie.value
    elif cookie.name == dts:
        dts_value = cookie.value
    elif cookie.name == dcc:
        dcc_value = cookie.value
    elif cookie.name == nid:
        nid_value = cookie.value


cookie_dict = {
    "__Secure-1PSID": psid_value,
    "__Secure-1PSIDTS": dts_value,
    "__Secure-1PSIDCC": dcc_value,
}
session = requests.Session()
session.cookies.set("__Secure-1PSID", psid_value)
session.cookies.set( "__Secure-1PSIDCC", dcc_value)
session.cookies.set("__Secure-1PSIDTS", dts_value)
session.cookies.set("NID",nid_value)
session.headers = SESSION_HEADERS

bard = BardCookies(session=session,cookie_dict=cookie_dict)

while True:

    question = input("Enter your prompt to Gemini: ")
    response = bard.get_answer(question)['content']
    data = str(response).replace("*", "")
    print(data)
    
``` 
[Updated files.zip](https://github.com/dsdanielpark/Bard-API/files/14228730/Updated.files.zip)

**Comment by J-Fo-S** [comment]
Here's a new wrinkle. I now obtain a Secure-1PSID that does not end with a dot. When I place the string in my code I get the following error:

> Exception: __Secure-1PSID value must end with a single dot. Enter correct __Secure-1PSID value

If I add the dot, it of course does not work. I do notice a dot now appears after the first character of the string, in my case it starts of like:
> g.a000

Not sure if this is random or the new placement of the dot.

**Comment by nicolaslr75** [comment]
@aniruddhkrish 

File "XXXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by aniruddhkrish** [comment]
@J-Fo-S 
 

Use this code,
```python
from bardapi import SESSION_HEADERS, BardCookies
import browser_cookie3
import requests
domain = '.google.com'

firefox_cookies = browser_cookie3.firefox(domain_name=domain)

psid = '__Secure-1PSID'
dts = '__Secure-1PSIDTS'
dcc = '__Secure-1PSIDCC'
nid = 'NID'

psid_value = None
dts_value = None
dcc_value = None
nid_value = None

for cookie in firefox_cookies:
    if cookie.name == psid:
        psid_value = cookie.value
    elif cookie.name == dts:
        dts_value = cookie.value
    elif cookie.name == dcc:
        dcc_value = cookie.value
    elif cookie.name == nid:
        nid_value = cookie.value


cookie_dict = {
    "__Secure-1PSID": psid_value,
    "__Secure-1PSIDTS": dts_value,
    "__Secure-1PSIDCC": dcc_value,
}
session = requests.Session()
session.cookies.set("__Secure-1PSID", psid_value)
session.cookies.set( "__Secure-1PSIDCC", dcc_value)
session.cookies.set("__Secure-1PSIDTS", dts_value)
session.cookies.set("NID",nid_value)
session.headers = SESSION_HEADERS

bard = BardCookies(session=session,cookie_dict=cookie_dict)

while True:

    question = input("Enter your prompt to Gemini: ")
    response = bard.get_answer(question)['content']
    data = str(response).replace("*", "")
    print(data)

``` 
Pass the 4 cookies. It will work. Do it as done above.

**Comment by aniruddhkrish** [comment]
@nicolaslr75 

Did you unzip the updated files and replaced the original ones in the appropriate folder with them?

**Comment by aniruddhkrish** [comment]
@nicolaslr75 
Attached is the zipped folder of the updated files (core.py, constant, core_cookies.py). Replace the original ones with the ones in the folder of updated files. 

Then run the code given above by me in my last comment. Make sure to use a reusable session with session headers.

**Comment by J-Fo-S** [comment]
> @J-Fo-S
> 
> Use this code,
> 
> ```python
> from bardapi import SESSION_HEADERS, BardCookies
> import browser_cookie3
> import requests
> domain = '.google.com'
> 
> firefox_cookies = browser_cookie3.firefox(domain_name=domain)
> 
> psid = '__Secure-1PSID'
> dts = '__Secure-1PSIDTS'
> dcc = '__Secure-1PSIDCC'
> nid = 'NID'
> 
> psid_value = None
> dts_value = None
> dcc_value = None
> nid_value = None
> 
> for cookie in firefox_cookies:
>     if cookie.name == psid:
>         psid_value = cookie.value
>     elif cookie.name == dts:
>         dts_value = cookie.value
>     elif cookie.name == dcc:
>         dcc_value = cookie.value
>     elif cookie.name == nid:
>         nid_value = cookie.value
> 
> 
> cookie_dict = {
>     "__Secure-1PSID": psid_value,
>     "__Secure-1PSIDTS": dts_value,
>     "__Secure-1PSIDCC": dcc_value,
> }
> session = requests.Session()
> session.cookies.set("__Secure-1PSID", psid_value)
> session.cookies.set( "__Secure-1PSIDCC", dcc_value)
> session.cookies.set("__Secure-1PSIDTS", dts_value)
> session.cookies.set("NID",nid_value)
> session.headers = SESSION_HEADERS
> 
> bard = BardCookies(session=session,cookie_dict=cookie_dict)
> 
> while True:
> 
>     question = input("Enter your prompt to Gemini: ")
>     response = bard.get_answer(question)['content']
>     data = str(response).replace("*", "")
>     print(data)
> ```
> 
> Pass the 4 cookies. It will work. Do it as done above. Make sure you have installed Firefox and signed in there.

@aniruddhkrish While this doesn't quite address the error I described while operating on Chrome, I can confirm this solution works on FireFox IF you also manually set the headers as you describe [here](https://github.com/dsdanielpark/Bard-API/issues/275#issuecomment-1936045704)

**Comment by aniruddhkrish** [comment]
@J-Fo-S 

You can also try using edge by removing firefox.

**Comment by aniruddhkrish** [comment]
While operating chrome, you get that errors because chrome does not permit you to access cookies through browser_cookie3 but firefox does.

**Comment by aniruddhkrish** [comment]
@J-Fo-S  I tried using Edge but it does not work. It works seamlessly through Firefox.

**Comment by sapycola** [comment]
from bardapi.constants import (
    ALLOWED_LANGUAGES,
    SESSION_HEADERS,
    TEXT_GENERATION_WEB_SERVER_PARAM,
    Tool,
    POST_ENDPOINT,
)

exception after copy file.zip

ImportError: cannot import name 'POST_ENDPOINT' from 'bardapi.constants' (C:\Python312\Lib\site-packages\bardapi\constants.py)
python-BaseException

**Comment by aniruddhkrish** [comment]
@sapycola its working for me. I imported POST_ENDPOINT

**Comment by aniruddhkrish** [comment]
Click that and try changing the POST_ENDPOINT POST_ENDPOINT = "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate"
to "POST_ENDPOINT = "https://gemini.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate"

**Comment by dsdanielpark** [comment]
We are currently working on modifying the previous bardapi to make it usable on Gemini. Both this repository and the gemini-api repository will be synced for a while to minimize confusion for users.

Once the work is complete, we will release bardapi version 0.1.40 and python-gemini-api version 0.1.2. Thank you.

**Comment by sambitweeting** [comment]
Error even after using updated file for gemini

```
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 332, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by sambitweeting** [comment]
> We are currently working on modifying the previous bardapi to make it usable on Gemini. Both this repository and the gemini-api repository will be synced for a while to minimize confusion for users.
> 
> Once the work is complete, we will release bardapi version 0.1.40 and python-gemini-api version 0.1.2. Thank you.

Let us know once done.

**Comment by dsdanielpark** [comment]
> @Goodday777
> 
> I have found the solution for this.
> 
> But I think this only works with Firefox browser.
> 
> Here are the steps to use the latest Gemini AI through Bardapi with some kind of stability.
> 
> Install Firefox.
> 
> Sign in to Gemini (formerly Bard) with your google account credentials.
> 
> Unzip the updated files which are attached here and place it in the appropriate folders
> 
> Then you will be able to use bardapi seamlessly with the following code. Every time you run this code, it will extract the new cookies from firefox and send it to bardapi. Make sure to pip install browser_cookie3.
> 
> ```python
> import requests
> from bardapi import SESSION_HEADERS, BardCookies
> import browser_cookie3
> 
> domain = '.google.com'
> 
> firefox_cookies = browser_cookie3.firefox(domain_name=domain)
> 
> psid = '__Secure-1PSID'
> dts = '__Secure-1PSIDTS'
> dcc = '__Secure-1PSIDCC'
> nid = 'NID'
> 
> psid_value = None
> dts_value = None
> dcc_value = None
> nid_value = None
> 
> for cookie in firefox_cookies:
>     if cookie.name == psid:
>         psid_value = cookie.value
>     elif cookie.name == dts:
>         dts_value = cookie.value
>     elif cookie.name == dcc:
>         dcc_value = cookie.value
>     elif cookie.name == nid:
>         nid_value = cookie.value
> 
> 
> cookie_dict = {
>     "__Secure-1PSID": psid_value,
>     "__Secure-1PSIDTS": dts_value,
>     "__Secure-1PSIDCC": dcc_value,
> }
> session = requests.Session()
> session.cookies.set("__Secure-1PSID", psid_value)
> session.cookies.set( "__Secure-1PSIDCC", dcc_value)
> session.cookies.set("__Secure-1PSIDTS", dts_value)
> session.cookies.set("NID",nid_value)
> session.headers = SESSION_HEADERS
> 
> bard = BardCookies(session=session,cookie_dict=cookie_dict)
> 
> while True:
> 
>     question = input("Enter your prompt to Gemini: ")
>     response = bard.get_answer(question)['content']
>     data = str(response).replace("*", "")
>     print(data)
>     
> ```
> 
> [Updated files.zip](https://github.com/dsdanielpark/Bard-API/files/14228730/Updated.files.zip)

When setting four cookie values as session cookie values, it does not execute properly. Could it be that someone succeeded by adding additional cookie values in the Firefox browser? If anyone has succeeded with different cookie values, please let me know. If you have any experimental code that works correctly, please share it. It would greatly help with the update.

Alternatively, if needed, anyone can submit a pull request at any time.

Thank you.

**Comment by aniruddhkrish** [comment]
@dsdanielpark You need not to use the NID cookie.

**Comment by aniruddhkrish** [comment]
As you said, it is creating problems

**Comment by aniruddhkrish** [comment]
> Error even after using updated file for gemini
> 
> ```
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 332, in get_answer
>     resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
>                            ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
> IndexError: list index out of range
> ```

Do you use NID cookie? If yes, remove it. It worked for me.

**Comment by dsdanielpark** [comment]
[aniruddhkrish](https://github.com/aniruddhkrish)

Which cookies do you used? I will start from there.

**Comment by aniruddhkrish** [comment]
I used Secure 1PSID, Secure 1PSIDCC, Secure 1PSIDTS

**Comment by sambitweeting** [comment]
> > Error even after using updated file for gemini
> > ```
> >         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 332, in get_answer
> >     resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
> >                            ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
> > IndexError: list index out of range
> > ```
> 
> Do you use NID cookie? If yes, remove it. It worked for me.

Yes I use NID Cookie. I will try it removing NID

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
