### ISSUE TITLE
New Feature request. 

### ISSUE THREAD

**Issue by arin-prashar** [dsdanielpark/Bard-API#28]
I want a function that can assist in getting quotes from the Bard. 
I find it annoying to use get_answer() to get a quote when we can have a command for it.

**Comment by dsdanielpark** [comment]
Let me know what quote you are referring to. 

If necessary, please send it to me via email. 

The Bard() class has been designed to be as lightweight as possible, with many features removed. Could you please explain if the functionality you are requesting is essential, widely applicable, and commonly used? Alternatively, if you believe it is a valid addition, please submit a pull request after implementing the feature, and we will consider merging it as needed. 

Also, Check if the following is the use case you are referring to.

```python
prefix_command = "Give a random quote"
input_text = "in france"
Bard(token='xxx').get_answer(prefix_command+input_text)
```

**Comment by dsdanielpark** [comment]
The requested pull request can be addressed in a simpler way as follows. Code duplication decreases usability and efficiency. In particular, the request and response functions are more important. Additionally, adding unnecessary methods can cause confusion for other users. There are various other reasons, but I recommend using the code as shown below, and I will close this issue.

Furthermore, the translation code in the current pull request has been removed in the PyPI distribution version for reasons of code efficiency and generality.

There were more diverse and advanced features, but they were excluded to enable reuse as a variety of modules. Therefore, I cannot accept the pull request.

Thank you.

```python
quote_number= 1
quote_type= "random"

quote = Bard(token='xxx').get_answer(f"{quote_number} {quote_type} Quote")["content"]
```
