### ISSUE TITLE
Cookies refreshing very often and getting 429 all the time

### ISSUE THREAD

**Issue by skalaydzhiyski** [dsdanielpark/Bard-API#285]
Hey guys,

I am trying to get gemini to work, but the cookies are refreshed too quickly for me to be able to even even type them in my code.

Does anyone have working example I can try to follow :(

I am using linux and am sending the requests from the UK.

**Comment by dsdanielpark** [comment]
On processing, I will try to use brower_cookie3 to automatically update cookies which are changed very quickly.

**Comment by dsdanielpark** [comment]
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API
