### ISSUE TITLE
Context understanding

### ISSUE THREAD

**Issue by MohitSM18** [dsdanielpark/Bard-API#30]
Bard().get_answer(query1)['content']
Bard().get_answer(query2)['content']
The problem with this is that it does not remember the context what was asked in the first query, like Bard actually does. How can we make it remember context when running through API

**Comment by prashantsmp** [comment]
[https://github.com/dsdanielpark/Bard-API#reusable-session-object](url)

You can go through the above link.

**Comment by MohitSM18** [comment]
Thanks.. I just figured it out after posting the query :D

**Comment by dsdanielpark** [comment]
> [https://github.com/dsdanielpark/Bard-API#reusable-session-object](url)
> 
> You can go through the above link.


Thank you for the helpful answer. Close this issue.
