### ISSUE TITLE
Regenerate draft/Edit prompt

### ISSUE THREAD

**Issue by mat1rus** [dsdanielpark/Bard-API#35]
Is there a way to regenerate a draft or edit a prompt? I can't find a way to do any of them.

**Comment by dsdanielpark** [comment]
It is unclear which prompt requires clarification. Please specify the desired action you are referring to.

**Comment by mat1rus** [comment]
Look.
When asking Google Bard something on https://bard.google.com/, you have a little pencil on the right of your message which lets you to edit your prompt. On Bard's response, you can regenerate draft or select one of three generated drafts (or regenerate them too).

**Comment by mat1rus** [comment]
Oh, and also rating responses. That would be cool even if this is waste of time.

**Comment by GordonLevy** [comment]
> Oh, and also rating responses. That would be cool even if this is waste of time.

Nah, its really a waste of time as of now!

**Comment by mat1rus** [comment]
> > Oh, and also rating responses. That would be cool even if this is waste of time.
> 
> Nah, its really a waste of time as of now!

Yeah, this is. But at least editing prompt and regenerating draft is useful at least in some way.

**Comment by GordonLevy** [comment]
> Yeah, this is. But at least editing prompt and regenerating draft is useful at least in some way.

That's more of UI implementation tbh. You can configure the UI to edit a provided prompt or re-gen it using the existing API implementation

**Comment by dsdanielpark** [comment]
If we use a reusable session and avoid establishing a new connection for each request, it will likely reduce the overall time.

Secondly, try utilizing the timeout variable.

In fact, the Python program itself does not have a significant impact on latency.

The 'Prompt edit' feature you mentioned essentially involves modifying the existing prompt to fulfill my request. In reality, using Python, it can be resolved more easily by directly modifying the text and pressing Enter.

Therefore, there are no further errors to be resolved regarding this issue, so I am closing it.
