### ISSUE TITLE
Provide Links For Images Generated by Google's Bard AI

### ISSUE THREAD

**Issue by GordonLevy** [dsdanielpark/Bard-API#36]
Hello,

It seems BardAI now supports image generation as per below snapshot. However the Bard-API only returns the alt-image-text for the generated image.
Is there a way to include the links of the generated images?

**Comment by dsdanielpark** [comment]
Thank you for bringing up this interesting issue. While there is a high possibility that it may not work, I will investigate it further.

**Comment by GordonLevy** [comment]
Would really like it to have the links of generated images, maybe put a network interceptor to catch hold of these links?

**Comment by dsdanielpark** [comment]
<img width="911" alt="bard_links" src="https://github.com/dsdanielpark/Bard-API/assets/81407603/b0f19557-6c04-4927-96f1-7a9219e35b37">

Bard is a language model, not an image generation AI model. However, I have recently confirmed the addition of the image web search feature to Google Bard. As a temporary solution, it returns the links included in the response. Please note that this feature is temporary and is only deployed in the developer version. Please use it as follows.

```
pip install git+https://github.com/dsdanielpark/Bard-API.git
```

```
#pip install git+https://github.com/dsdanielpark/Bard-API.git
from bardapi import Bard
bard = Bard(token='xxxxxxxxxxx')
res = bard.get_answer("Find me an image of the main entrance of Stanford University.")
res['links']
```

**Comment by GordonLevy** [comment]
Yes, from the images response list - it looks the the uri for generated image is : t0.gstatic.com/images
which could be appended in the response string.

Any timelines around which this feature is deployed to prod?

**Comment by dsdanielpark** [comment]
> 

It is not desirable to continuously add specific functionalities to the developer deployment version. Therefore, we recommend post-processing and using the following approach instead.

```python
token='xxxxxxxx'
bard = Bard(token=token)
link_list = bard.get_answer("Find me an image of the main entrance of Stanford University.")['links']
filtered_links = [link for link in link_list if "https://lh3.googleusercontent.com/" in link or "http://t0.gstatic.com/" in link]

print(filtered_links)
```

**Comment by GordonLevy** [comment]
Thanks for your detailed response, just have one final query : Any timelines around which this feature is deployed to prod?

**Comment by dsdanielpark** [comment]
Please check this commit hash `acbf3fba8453ea354a0b53e59230175a44500171`

**Comment by acheong08** [comment]
https://github.com/acheong08/Bard/compare/1.0.3...1.1.0

You can parse for images
```py
if len(json_chat_data) >= 3:
            for img in json_chat_data[4][0][4]:
                images.add(img[0][0][0])
```

**Comment by dsdanielpark** [comment]
[acheong08](https://github.com/acheong08)
```
images = set()
        if len(json_chat_data) >= 3:
            if len(json_chat_data[4][0]) >= 3:
                for img in json_chat_data[4][0][4]:
                    images.add(img[0][0][0])
```
Could you contribute by including this part and the part where "images" is the key?

**Comment by acheong08** [comment]
```python
chat_data = json.loads(resp.content.splitlines()[3])[0][2]
if not chat_data:
    return {"content": f"Google Bard encountered an error: {resp.content}."}
json_chat_data = json.loads(chat_data)
images = set()
if len(json_chat_data) >= 3:
    if len(json_chat_data[4][0]) >= 4:
        for img in json_chat_data[4][0][4]:
            images.add(img[0][0][0])
results = {
    "content": json_chat_data[0][0],
    "conversation_id": json_chat_data[1][0],
    "response_id": json_chat_data[1][1],
    "factualityQueries": json_chat_data[3],
    "textQuery": json_chat_data[2][0] if json_chat_data[2] is not None else "",
    "choices": [{"id": i[0], "content": i[1]} for i in json_chat_data[4]],
    "images": images,
}
```

**Comment by dsdanielpark** [comment]
[acheong08](https://github.com/acheong08)

Thank you, then I will modify and commit.

**Comment by GordonLevy** [comment]
> Please check this commit hash `acbf3fba8453ea354a0b53e59230175a44500171`

Was looking to have this feature in the official pip package - 'bardapi'

**Comment by dsdanielpark** [comment]
Use developer version or you can install via github tag. Refere this CoCoder package. https://github.com/dsdanielpark/Co-Coder/blob/main/requirements.txt

**Comment by MohitSM18** [comment]
> <img alt="bard_links" width="904" src="https://user-images.githubusercontent.com/81407603/240504845-36a11f95-662d-4739-9957-2c2d7b822f25.png">
> 
> Bard is a language model, not an image generation AI model. However, I have recently confirmed the addition of the image web search feature to Google Bard. As a temporary solution, it returns the links included in the response. Please note that this feature is temporary and is only deployed in the developer version. Please use it as follows.
> 
> ```
> pip install git+https://github.com/dsdanielpark/Bard-API.git
> ```
> 
> ```python
> from bardapi import Bard
> bard = Bard(token='xxxxxxxxxxx')
> res = bard.get_answer("Find me an image of the main entrance of Stanford University.")
> res['links']
> ```

Hi Daniel, this works in Google colab and gives the links, but doesn't work on Jupyter notebook; why so?

**Comment by dsdanielpark** [comment]
[MohitSM18](https://github.com/MohitSM18)

There could be various reasons for the issue. If it continues to not work on your local Jupyter Notebook, please feel free to create a new issue. Thank you.
