### ISSUE TITLE
Chat continuity not working?

### ISSUE THREAD

**Issue by gvu6c** [dsdanielpark/Bard-API#39]
I wanted to try to continue the chat and tried the code as per the sample in the readme, but it returns a completely different prompt on the second question.

Is there any way to fix this?

**Comment by dsdanielpark** [comment]
I have confirmed that it is now functioning correctly. Please refrain from re-executing or passing the Bard object a session again. 

Upon reviewing your repository, I noticed that there is no process of creating a session object and passing it as an argument. It seems that there is a need to modify the entire pipeline accordingly.
