### ISSUE TITLE
Need to have embedding support  for bardapi 

### ISSUE THREAD

**Issue by sanjay7178** [dsdanielpark/Bard-API#43]

**Comment by dsdanielpark** [comment]
Please designate me as a co-author and open the repository. 

Once you provide a space for BardAPI or specify where it can be incorporated, I will assist you within a reasonable timeframe. However, it's worth noting that BardAPI is already being used by a diverse range of projects and there are many well-implemented examples available. It can be beneficial to study and learn from those excellent code examples. Thank you.

**Comment by sanjay7178** [comment]
Main point want to create a this unoffical bardapi  support with langchain  , where then we can use in various projects like BardPDF where this api needs to work semantic search upon vector database made with text embedding models and also we can integrate this api in vs code where openai costs more on every api call
