### ISSUE TITLE
Response error 

### ISSUE THREAD

**Issue by Ansh-Sonkusare** [dsdanielpark/Bard-API#49]
I did as the docs said and just replaced my api key yet I m getting the error 

```py
from bardapi import Bard
import os

#Replace XXXX with the values you get from __Secure-1PSID 
os.environ['_BARD_API_KEY']="XXXX"
# set your input text
input_text = "what is google bard?"

print(Bard().get_answer(input_text)['content'])
```

``Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",329],["af.httprm",329,"2550290118937250235",0]]\n25\n[["e",4,null,null,131]]\n'.``

**Comment by izellevy** [comment]
I am getting the same error

**Comment by dsdanielpark** [comment]
I thought some API interface of google was changed. Try to figure out some change.

**Comment by dsdanielpark** [comment]
Please try this code and if you have a trouble. Please debugging and make it stable and ask PUll REQUEST. 

[Bard Cookies](https://github.com/dsdanielpark/Bard-API/blob/main/README_DEV.md#bard-which-can-get-cookies)

```python
from bardapi import BardCookies

cookies = {
    '__Secure-1PSID': 'xxxxxxxxxxx',
    'APISID' : 'xxxxxxxxxxx',
    'SAPISID' : 'xxxxxxxxx'
}

bard = BardCookies(cookies=cookies)
resp = bard.get_answer("hi")

resp['content']
```

**Comment by dsdanielpark** [comment]
First of all, it has been confirmed that it is not a change in Google Bard's internal API interface.

So look at #1 and check out the different possibilities.

This issue will be closed as duplicate.
