### ISSUE TITLE
Suggesting to add support behind proxy

### ISSUE THREAD

**Issue by nirlotan** [dsdanielpark/Bard-API#5]
Hi,
Thanks for creating this library! It is awsome, easy to use and very useful!
I'm using it behind a proxy, so I added support for proxies locally and would love to contribute it to the library if you agree.
If so - please let me know if you want me to branch, propose a solution and create a pull request.
Thanks!
Nir.

**Comment by dsdanielpark** [comment]
It seems like a very useful solution. I don't know how long Google Bard's interface will be valid, but I'd be very happy if you could contribute a solution to it. It would be nice if you could contribute along with some documentation without disturbing the structure of the original package. After contributing, please submit a Pull Request.

**Comment by dsdanielpark** [comment]
Thank you, [nirlotan](https://github.com/nirlotan)

Close the issue with a successful solution. Thank you for your contribution. 
Due to GitHub delays, you should see your name in the repository contribution section within 24 hours.

Regards,
Park

**Comment by dsdanielpark** [comment]
I didn't know someone else had a pull request.

Please make a pull request again after doing a little refactoring related to the proxy. please send me a pull request and I'll merge it again. Sorry for the misunderstanding the name of requester. 

Regards,
Park
