### ISSUE TITLE
Cannot be used from japan (Bard PSID cookie update?)

### ISSUE THREAD

**Issue by MeemeeLab** [dsdanielpark/Bard-API#50]
I don't know this is specific to me or only rolled out to japan region, but from what I can see now, bard.google.com does not allow logging in just by sending `__Secure-1PSID` now.
This causes "SNlM0e value not found in response. Check __Secure-1PSID value." error with valid __Secure-1PSID token.

I tried different cookie combination, and found out now it needs 3 cookies:
 * __Secure1-PSID
 * APISID
 * SAPISID

I noticed this library was becoming unstable yesterday (It wasn't unstable before that) and today, it became completly unusable.

Would be appreciated if you can make cookie dict parameter instead of just one PSID str argument.

Thanks

**Comment by dsdanielpark** [comment]
Thank you for your report. 

And I would be happy if you can contribute. But I will fix this issue after 24 hours. 

Thank you, Again.

**Comment by dsdanielpark** [comment]
Please try this code and if you have a trouble. Please debugging and make it stable and ask PUll REQUEST. 

[Bard Cookies](https://github.com/dsdanielpark/Bard-API/blob/main/README_DEV.md#bard-which-can-get-cookies)

**Comment by 25077667** [comment]
It seems still not work on my machine:

![image](https://github.com/dsdanielpark/Bard-API/assets/16622598/a4cb46c1-f7f1-4f60-bc23-163c7c4806dd)

**Comment by MeemeeLab** [comment]
Weird. I used code below and I checked it's sending cookies by debugging, but website does not return `SNlM0e` value. I can see other values, like `S06Grb` and `TSDtV`, but only `SNlM0e` missing.
From chrome devtools, requests sent from browser has response with SNlM0e, so I think this is not update to entire system, but just weird.

I'll continue to try it and will post here if I have any updates
```
from bardapi import BardCookies

cookie_dict = {
    "__Secure-1PSID": "...",
    "APISID": "...",
    "SAPISID": "..."
}

bard = BardCookies(token=cookie_dict["__Secure-1PSID"], cookie_dict=cookie_dict)

print(bard.get_answer("こんにちは"))
```

**Comment by MeemeeLab** [comment]
Ok, so I tried different cookie combination again, and it is now requiring `__Secure-1PSID` and `__Secure-1PSIDTS`?
I'm sure I was getting SNlM0e with `__Secure-1PSID` and `APISID` and `SAPISID` yesterday.

It might be google trying to change alogrithms because I'm sending too many requests (I'm not spamming but it might be too much for google?) or in my region...

I think it's more safe to pass all cookies, so I think it needs removal hard-coded cookie assigns on `BardCookies`.

I might send PR when available, thanks for your support!

**Comment by dsdanielpark** [comment]
Most likely it was a temporary ban.

Thanks for reporting though.
