### ISSUE TITLE
How do I get it to respond without saying "Sure" then repeating the prompt

### ISSUE THREAD

**Issue by JVTEAM** [dsdanielpark/Bard-API#52]
This is an issue on the web version as well, but I would rather it just answer rather than saying "sure, here's the capital of france"

When I asked it, it said to use bard -n in front of the prompt, however that doesn't seem to work.

**Comment by dsdanielpark** [comment]
You can use it by pre-processing and post-processing as follows. Some prompts, such as "-n" in prompt engineering, can also be handled as part of the logic for use. The bardapi package does not include these functionalities to allow customization by many users regarding various options.

```python
from bardapi import Bard

def process_text(text):
    split_text = text[:100].split(".")
    
    if len(split_text) > 0 and any("sure" in sentence.lower() for sentence in split_text[0].split()):
        split_text = split_text[1:]
    
    processed_text = ".".join(split_text) + text[100:]
    return processed_text


token = 'xxxxxxx'
bard = Bard(token=token)
answer = bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']

answer = process_text(answer)
```
