### ISSUE TITLE
Response error

### ISSUE THREAD

**Issue by agniiva** [dsdanielpark/Bard-API#53]
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",253],["af.httprm",252,"7953890135670054436",0]]\n25\n[["e",4,null,null,131]]\n'.

<img width="896" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/73607864/757d7240-ff44-4bb0-9abb-ff72378f4575">

**Comment by axcel0803** [comment]
Same 
![image](https://github.com/dsdanielpark/Bard-API/assets/30665647/b55ac775-ad18-4dad-8ba6-f5a24238e8d7)

**Comment by dsdanielpark** [comment]
Has there been an error recently with receiving responses, or has there been an error from the beginning? If it's been an issue from the start, please refer to the following this issue #1

**Comment by dsdanielpark** [comment]
Please review #1.
Since this is a duplicate issue and it is not causing any problems for other users simultaneously, I will close this issue.
