### ISSUE TITLE
Feature for remember previous chat or responses.

### ISSUE THREAD

**Issue by BabaYaga1221** [dsdanielpark/Bard-API#59]
hello, I am using your project and found one little thing: it is not saving or remembering the previous responses for better results. can you provide anything related to this issue? Thanks

**Comment by phamxtien** [comment]
Use  conversation_id

**Comment by dsdanielpark** [comment]
Here are two examples to consider depending on the context:

1. [reusable-session-object](https://github.com/dsdanielpark/Bard-API#reusable-session-object)
2. [fix-conversation-id-fix-context](https://github.com/dsdanielpark/Bard-API/blob/main/README_DEV.md#fix-conversation-id-fix-context)

**Comment by Arkuus** [comment]
> Here are two examples to consider depending on the context:以下是需要根据上下文考虑的两个示例：
> 
> 1. [reusable-session-object  可重用会话对象](https://github.com/dsdanielpark/Bard-API#reusable-session-object)
> 2. [fix-conversation-id-fix-context修复对话 ID 修复上下文](https://github.com/dsdanielpark/Bard-API/blob/main/README_DEV.md#fix-conversation-id-fix-context)
> 
> You can refer [this github](https://github.com/thecodekitchen/bardchat-python/blob/master/app/main.py) to check usage of conversation id.您可以参考这个github来检查对话id的使用情况。

Hello, I am currently using your project. I've built a web page with Flask, but I've failed to maintain the conversation content. I have tried your installation methods, but I still haven't been successful. Each conversation is new. Could you provide me with some solutions? Could it be that the methods are no longer valid due to the official update on July 13th?
Here's my app.py code:
```
from flask import Flask, render_template, request
from bardapi import Bard
import os
import requests
import json

app = Flask(__name__)

session = requests.Session()
session.headers = {
    "Host": "bard.google.com",
    "X-Same-Domain": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
    "Origin": "https://bard.google.com",
    "Referer": "https://bard.google.com/",
}
os.environ['_BARD_API_KEY'] = 'XXXXXX'
session.cookies.set("__Secure-1PSID", os.getenv("_BARD_API_KEY"))

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        user_input = request.form.get('user_input')
        token = os.environ["_BARD_API_KEY"]
        bard = Bard(token=token, session=session, timeout=30)
        response = bard.get_answer(user_input)
        ai_response = response['content']
        conversation_id = response['conversation_id']
        return json.dumps({'answer': ai_response, 'cid': conversation_id})
    return render_template('home.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)

**Comment by dsdanielpark** [comment]
It would be a good idea to check for follow-up issues regarding related content. While some persistence is possible through context IDs and sessions, a complete implementation is not feasible. Therefore, consider options such as creating a database or sending multiple conversation queries simultaneously. Thank you.
