### ISSUE TITLE
Getting errors even on first request, even with large timeout

### ISSUE THREAD

**Issue by josh-ashkinaze** [dsdanielpark/Bard-API#60]
I tried running this, and I am getting the same kind of error. I didn't make a lot of requests, and this error persists whether I vary the following factors:

- session: Tried with and without 
- timeout: Tried with and without  

Here's what the errors are:

```
Session and timeout: Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",207],["af.httprm",206,"-5973836830292919317",0]]\n25\n[["e",4,null,null,132]]\n'.

Session: Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",158],["af.httprm",157,"-7097826725018575708",1]]\n25\n[["e",4,null,null,132]]\n'.

Timeout: Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",188],["af.httprm",187,"-7191527685766192777",2]]\n25\n[["e",4,null,null,132]]\n'.

No Sesh No Timeout: Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",170],["af.httprm",170,"3959452704966963607",1]]\n25\n[["e",4,null,null,131]]\n'.
```

```
!pip install bardapi


from bardapi import Bard
import os
import requests

# Get this from going to 
# Bard web UI --> 
# Developer tools --> 
# Applications --> 
# Storage tab --> 
# cookies --> 
# Secure-1PSID
token='MYCOOKIE.'
session = requests.Session()
session.headers = {
            "Host": "bard.google.com",
            "X-Same-Domain": "1",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Origin": "https://bard.google.com",
            "Referer": "https://bard.google.com/",
        }
session.cookies.set("__Secure-1PSID", token)

# TRY DIFFERENT COMBOS OF SESSION AND TIMEOUT 

# Session and timeout 
bard = Bard(token=token, session=session, timeout=500)
ans = bard.get_answer("What's a creative use for a hat?")['content']
print("Session and timeout:", ans)

# Session
bard = Bard(token=token, session=session)
ans = bard.get_answer("What's a creative use for a hat?")['content']
print("Session:", ans)

# Timeout
bard = Bard(token=token, timeout=500)
ans = bard.get_answer("What's a creative use for a hat?")['content']
print("Timeout:", ans)

# No Session, No Timeout
bard = Bard(token=token)
ans = bard.get_answer("What's a creative use for a hat?")['content']
print("No Sesh No Timeout:", ans)
```

**Comment by jdixosnd** [comment]
It does not seem to be the issue of this library as bard itself throws error if it notices some pattern. In my case i am asking same question by changing some parameters. if I break the pattern by asking different question then it starts to work fine but only for couple of instances. 
As of now, I dont have any solid implementation that works but will try some logic to break such pattern.

**Comment by jdixosnd** [comment]
Did you ask questions again and again with same frequency as your code? I tried to replicate the same from the UI and I was greeted with the same error. Notice the popup on the bottom left side of the window. It clearly rejected my request from UI. And the error in the response of network seems similar to what we are getting from the API.

![image](https://github.com/dsdanielpark/Bard-API/assets/11541260/8d8db693-f39d-41a7-b16b-3b7e01627f98)

**Comment by josh-ashkinaze** [comment]
But you are asking a different question, which did throw an error on the UI. I am saying that my prompt did _not _ throw an error on the UI. Try asking: "What's a creative use for a hat?" several times. It does _not_ throw an error on the UI.
