### ISSUE TITLE
Problem when executing Bard.get_answer()

### ISSUE THREAD

**Issue by Yazeed-Alharbi** [dsdanielpark/Bard-API#67]
Earlier today, it was working fine but now whenever it executes it shows me this error: 

site-packages/bardapi/core.py", line 114, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
IndexError: list index out of range

**Comment by dsdanielpark** [comment]
If it is working properly and there are no errors reported by other users, please refer to the following issues. #1
