### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by PushkarOP** [dsdanielpark/Bard-API#72]
my code
from bardapi import Bard

token = 'xxxxxxxxxxxxxxxx'
bard = Bard(token=token)
a = bard.get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
print(a)

output
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",55],["af.httprm",55,"-5659935360951844781",29]]\n25\n[["e",4,null,null,131]]\n'.

**Comment by dsdanielpark** [comment]
There are various possibilities, and the details regarding them are very well summarized in the following issue. I hope you can find the solution to your bug in the next issue. As this is a duplicate issue, I will close it. #1
