### ISSUE TITLE
Suddenly got "'NoneType' object is not subscriptable error" when calling Bard().get_answer(prompt)

### ISSUE THREAD

**Issue by lesleychou** [dsdanielpark/Bard-API#78]
Hi, 

Thank you for putting together the API!

I've been using it for a week, it worked well. However this morning it suddenly shows an error like below:
```
response = Bard().get_answer(prompt)['content']
*** TypeError: 'NoneType' object is not subscriptable
```

May I ask if you know what is the cause of this error and how could we fix it? I feel it's from google's side.

Thank you!

**Comment by lesleychou** [comment]
Hi,

I found out ()from another repo's update that updating this line to the below could work: https://github.com/dsdanielpark/Bard-API/blob/b9a70cd7e624cd01136548d790ff754c224c15ee/bardapi/core.py#L147

```
"content": parsed_answer[4][0][1][0]
```

Could you confirm it? Thanks!

**Comment by dsdanielpark** [comment]
[lesleychou](https://github.com/lesleychou)

I have checked it. I will take care of the remaining parts and make the necessary modifications. Would you be able to submit a pull request with the updated content? Thank you for your contribution.

**Comment by dsdanielpark** [comment]
```
pip install bardapi>=0.1.18
```

Due to changes in the Google interface, a bug has been fixed in the temporary release of version 0.1.18. We are preparing for the release of version 0.1.19, which will include checks for the remaining features. Additionally, starting from version 0.1.18, the GitHub version of BardAPI will be synchronized with the PyPI version and released simultaneously.

**Comment by Kyoharo** [comment]
i have issue when try to use anther language that not in ALLOWED_LANGUAGES
the output of content bard_answer is : 
```
{'content': '*', 'conversation_id': 'c_72cbdc1a07a7a4a2', 'response_id': 'r_72cbdc1a07a7adb7', 'factualityQueries': None, 'textQuery': ['how are you', 1], 'choices': [{'id': 'rc_72cbdc1a07a7ab20', 'content': '**Bard**: Ciao Kyoharo, sto bene, grazie per avermelo chiesto! Sono entusiasta di poter aiutare le persone con i loro compiti e progetti creativi. Come stai oggi?'}, {'id': 'rc_72cbdc1a07a7a435', 'content': '**Bardo**: Ciao Kyoharo! Sto bene, grazie per avermelo chiesto. Sono entusiasta di poter aiutare le persone con i loro compiti e progetti creativi. Come stai oggi?'}, {'id': 'rc_72cbdc1a07a7ad4a', 'content': '**Bard**: Ciao Kyoharo, sto bene, grazie per avermelo chiesto! Sono entusiasta di poter aiutare le persone con i loro compiti e rispondere alle loro domande. Come stai oggi?'}], 'links': [], 'images': set(), 'code': None}
```
But when I use language from ALLOWED_LANGUAGES the content output is: 
```
{'content': '**Bard**: Hello there! How can I help you today?', 'conversation_id': 'c_fc8128445043a961', 'response_id': 'r_fc8128445043af54', 'factualityQueries': None, 'textQuery': ['hello', 1], 'choices': [{'id': 'rc_fc8128445043ad13', 'content': ['**Bard**: Hello there! How can I help you today?']}, {'id': 'rc_fc8128445043a306', 'content': ['**Bard**: Hello! How can I help you today?']}], 'links': [], 'images': set(), 'code': None}
```

**Comment by dsdanielpark** [comment]
[Kyoharo](https://github.com/Kyoharo)

Thank you. I apologize for checking this late due to other project tasks. I will review the information and make the necessary updates. I appreciate your contribution. Have a great day!
