### ISSUE TITLE
KeyError: 'images' when using ChatBard

### ISSUE THREAD

**Issue by Xiansssss** [dsdanielpark/Bard-API#84]
This is the code snippet I run:
'''
from bardapi import ChatBard
    
chat = ChatBard(token=token, language='en')
chat.start()
'''

Sometimes it pops up the keyerror, even if I modify the code in chat.py, is that a problem related to network? Note that I'm using a virtual network. Thanks guys.

<img width="927" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/23b165d2-906f-432f-9995-af9c8dc38ead">

**Comment by dsdanielpark** [comment]
This issue has been resolved in version 0.1.21. While not recommended, to save time due to other projects, we will briefly suppress the error using a try-except statement.
```
pip install bardapi==0.1.21
```

**Comment by Xiansssss** [comment]
Thanks bro, it really works. But there's still something wrong. I would really appreciate if you can help 
<img width="391" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/faeb6277-1d52-47d6-b6fa-1a71e760d455">
whatever I input, it doesn't respond. And furthermore, if I wanna modify the code in your module(bardapi), it always stay in the old version even if I run this :
<img width="470" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/60f20a4e-6787-4136-933b-0ff3f285b9ad">
