### ISSUE TITLE
cannot run chat bard on google colab or any server 

### ISSUE THREAD

**Issue by Xiansssss** [dsdanielpark/Bard-API#85]
hey bro, the model will always repeat what I say when I run the code on the colab or server  do you know what's going on ？Thanks  a lot.

<img width="441" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/0d29026c-6732-4d13-9131-1fdb7bceb921">

**Comment by dsdanielpark** [comment]
This error has been fixed in version 0.1.22. There was a misunderstanding during the process of modifying the previous code.

```
pip install bardapi==0.1.22
```

**Comment by Xiansssss** [comment]
<img width="461" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/a93ba3f3-aacc-4aa4-a587-e22920d371d5">
bro it still remains.

**Comment by dsdanielpark** [comment]
Does the following command work correctly?
```python
bard.get_answer("YOUR QUEST")
```

Before using the chat, I'm curious if the `Bard.get_answer` method is functioning properly.
