### ISSUE TITLE
error when run chat bard on google colab or any server 

### ISSUE THREAD

**Issue by Xiansssss** [dsdanielpark/Bard-API#87]
<img width="576" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/82095274/0d131fdc-d479-4f51-a1ac-52304009340a">
when I run the code, it doesn't make any response and just always wait for input  whatever I say.
Really appreciate for your response.

**Comment by dsdanielpark** [comment]
Please utilize the existing issue for duplicate reports. Additionally, please ensure that you are using the latest version of bardapi. This issue may be influenced by version and network-related factors, so we would appreciate more detailed information.
