### ISSUE TITLE
Training Bard

### ISSUE THREAD

**Issue by SiamOfficial** [dsdanielpark/Bard-API#89]
Is there a way I can train the bard on my own?

**Comment by dsdanielpark** [comment]
Please refer to the README.md. This is an unofficial project undertaken by individuals, designed to test only certain functionalities before the official API for Bard is released. Additionally, Bard is not free, and the current approach is a project aimed at assisting developers in implementing and verifying features.

Therefore, support for features beyond training is not available. For tasks such as training or fine-tuning, please refer to resources like Llama.
