### ISSUE TITLE
cannot import name 'get_host' from 'urllib3.util.url' 

### ISSUE THREAD

**Issue by zeelsheladiya** [dsdanielpark/Bard-API#9]
I am using MacBook and I am encountering this issue while I am running the scripts. 

This issue appears to be in bardapi/core.py in the import request library.

<img width="1098" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/46935793/fc9612ee-eb12-4e48-a9fa-7bcacd5ef1e0">

**Comment by dsdanielpark** [comment]
Try uninstalling and reinstalling in your `venv` as follows.

```
pip uninstall urllib3 -y
pip uninstall requests -y
```
```
pip install --upgrade urllib3
pip install --upgrade requests
```

**Comment by zeelsheladiya** [comment]
Thank you so much. It issue has been solved by your help.
