### ISSUE TITLE
Suggest new chat feature

### ISSUE THREAD

**Issue by itsmeshashank13** [dsdanielpark/Bard-API#91]
* A new chat option for each new chat a person wants to do.
* The chats should be saved so that users can review them at any time.
* The chat threads could be organized by date, topic, or user.
* The chat threads could also be tagged with keywords so that users can easily search for them.

**Comment by dsdanielpark** [comment]
Thank you for the very intriguing suggestion. Implementing the Python version of the proposed content is not difficult. However, it would be more desirable to implement this functionality in frontend or backend development, as it would also be beneficial for database management.

**Comment by dsdanielpark** [comment]
Features like ChatBard are now updated in both the latest release and the main branch. Therefore, we will close this issue. Thank you.

**Comment by itsmeshashank13** [comment]
Thank you for the update! I appreciate your quick action in addressing this issue. Really appreciate it.

**Comment by dsdanielpark** [comment]
Some features are ready. I will fix documents.
