### ISSUE TITLE
SNlM0e value not found Error.

### ISSUE THREAD

**Issue by jongwonJeong** [dsdanielpark/Bard-API#96]
Hi. I appreciate the API provided. Unfortunately, I found an error occurred in API, and reporting it is necessary for your API improvement.

Although there is no error that occurred with the same __Secure-1PSID before today, I have found that the same value of __Secure-1PSID value induces the error like "Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'."

The error figure is as follows.

![image](https://github.com/dsdanielpark/Bard-API/assets/38099724/155fd8c3-1dd6-4663-989f-27d5873776e5)

Could you check this? Thanks.

P.s. the version of bardapi is 0.1.24.

**Comment by jongwonJeong** [comment]
> Hi, I encountered the same issue, have you found any solutions?

Yeah, yesterday, I found out that deleting all cache in Chrome and restarting Chrome can resolve this issue.

Sorry for the late response and closing this issue. I hope you can get help with this reply.

**Comment by leguicriarg** [comment]
Check your token. You must get it using Chrome (using incognito)
