### ISSUE TITLE
Exception: SNlM0e value not found.

### ISSUE THREAD

**Issue by timtaotao** [dsdanielpark/Bard-API#97]
I encountered this issue, and I can confirm that I was using the correct __Secure-1PSID value, and I could normally access the bard service. Last time I used my account didn't have this issuse.

Thanks.

**Comment by Thilo-Hagendorff** [comment]
Same problem. Has it something to do with a VPN? I'm trying to access the API from Germany.

**Comment by Uday-461** [comment]
any solution?

**Comment by Thilo-Hagendorff** [comment]
I disconnected the VPN, deleted all cookies, reconnected the VPN, reloaded the page, copied the newly generated token, and it worked.

PS: Since it is not possible to change any parameters like temperature, though, I assume the API is not of much help, at least for research.

**Comment by timtaotao** [comment]
@Thilo-Hagendorff Thanks, maybe the newly generated token worked. I have two other accounts, work just fine under the same internet condition, only my main account encountered this problem. I will try to solve this by deleting cookies.

**Comment by nikk-16** [comment]
There is no issue int this API. 
But after excessive usage, the Google knows that cookie is having unauthorized access so the 1PSID is revert in some form. 

The reason we get : Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'

How can you get rid of it: 
Clear cookies of bard.google.com and again 
- login into the account
- F12 > Applications > Cookies > bard > __Secure-1PSID
- Copy cookie and paste into your code.

Re run and you are good to go.

**Comment by timtaotao** [comment]
> 

After regenerating tokens, problem solved. I bieleve that should be the reason why my token didn't work last time, but something quite interesting is that I seldom use my main account to use this api, the account I might have excessively usage worked just fine.
